<h1>Archives</h1>
<h2>&nbsp;</h2>
<br />
<ol>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Loreal.pdf" target="_blank">Beating the Odds : Remarkable Women in Science!</a><br />Women scientists share their experiences of choosing Science for their study and career overcoming the hurdles and odds in their lives.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Asia.pdf" target="_blank">Asia : Shaking up Tradition</a><br />A brief insight into the significant changes in the prospects for women scientists in the culturally diverse Asia.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Handbook.pdf" target="_blank">The Coming Gender Revolution in Science</a><br />An article in the Handbook of Science and Technology Studies.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/uscong.pdf" target="_blank">Indian Government Offers Helping Hand to Women Scientists</a><br />News on Women's Day Conference by DST in Science journal</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Maria-ed.pdf" target="_blank">Dr. Maria Goeppert Mayer</a><br />An Editorial in Resonance journal.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Sherry_Towers.pdf" target="_blank">A Case Study of Gender Bias at the Postdoctoral Level in Physics, and its Resulting Impact on the Academic Career Advancement of Females</a><br /> - by Sherry Towers</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Data.pdf" target="_blank">Data show extent of sexism in physics</a><br />Findings of an experiment on institutional sexism at one of America's high profile physics lab by Sherry Towers.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Equal.pdf" target="_blank">Equal pay for women in science is achievable</a><br />Aggressive academic management can correct pay disparities between male and female scientists, say researchers.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Recruiters.pdf" target="_blank">Dr Jeykyll and Ms Hyde</a><br />Where are the women in science? And what would attract them from other sectors?</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Leaks.pdf" target="_blank">Leaks in the pipeline : Why do women remain curiously absent from the ranks of academia?</a><br />An interesting article in the journal Nature.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Bias.pdf" target="_blank">Bias cut</a><br />Women, it seems often get a raw deal in science; so how can discrimation be tackled?</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Nurture.pdf" target="_blank">Nurturing Women Scientists</a><br />A brief analysis of the survey on the professional development of women scientists in academia and industry.</li>
	<li class="journal-article-list"><a href="Fixing_the_Leaky_Pipeline">Fixing the Leaky Pipeline : Why aren't there many women in the top spots in the academia?</a><br />An article by Prof. Phoebe Leboy.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Allthings.pdf" target="_blank">All things equal</a><br />The article considers the issue of lack of affordable child care as a major impediment to women's careers in science.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/campus_child_care.pdf" target="_blank">Small steps towards campus child care</a><br />The article looks at the options available for working mums who find child care as a major obstabcle to getting back to the lab.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Europe.pdf" target="_blank">Special Report</a><br />Europe is pushing to get more women scientists into industry and academia, but can the commission legislate for gender equality? - Sally Goodman investigates.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Katz.pdf" target="_blank">Mentoring Women in the Biological Sciences: Is Informatics Leading the Pack?</a><br /> - by Samantha Katz</li>
	<li class="journal-article-list"><a href="Chinese_Scientists">One third Chinese scientists are women [What about India]</a><br />A news on an international seminar on women in science held in Beijing.</li>
	<li class="journal-article-list"><strong>Women in Physics</strong><br />A report in the Current Science journal about an international conference by the International Union of Pure and Applied Physics. Click here for more on <a href="http://physicsworld.com/" target="_blank">Physics</a>.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Nature.pdf" target="_blank">The Female Underclass</a><br />An article in the journal Nature, on the efforts done across Europe for improving the situation of women in science and research, based on the reports by the European Commission.</li>
</ol>
