<h1>Fixing the Leaky Pipeline</h1>
<h2>By Prof. Phoebe Leboy</h2>
<h4>Why aren't there many women in the top spots in academia?</h4>
<p class="img-with-caption"><img title="FIXING THE LEAKY PIPELINE" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/academia.jpg" alt="FIXING THE LEAKY PIPELINE"/></p>
<p>Back in 2006, I took a quick survey of the basic science departments in medical schools to see how women were doing in science. Close to half of the top 10 National Institutes of Health-funded academic health centers had no women among their junior tenure-track faculty in their biochemistry and cell biology departments. Looking at such statistics, a young woman might get the impression that her shot at the faculty positions at these schools would be difficult, if not out of reach. When I surveyed the schools, Harvard Medical School had 23 tenure-track faculty members in its cell biology and biochemistry/ molecular pharmacology departments, but none were women (since then, two women have joined the ranks). Why are so few women making it onto the tenure ladder at major medical schools?</p>
<p>These top institutions represent an extreme example of a general problem. For example, the NIH reports that only 20% of their senior scientists are women. Postdoctoral award data show that the biomedical pipeline is filled with good candidates, but disproportionately few get into the tenure track stream at major research institutions. Clearly some major leaks along the way are causing only a trickle of women to make it to the top.</p>
<h4>The postdoc to tenure track leak</h4>
<p>One of the most significant leaks in the pipeline occurs during the postdoc to tenure-track transition (EMBO Reports, 8:977-81, 2007). At the University of Pennsylvania, where I was on the faculty for 42 years, the basic science departments in the medical school had 18 women who were tenure-track assistant professors in 1999. By 2007 the number had dropped to four. In the past five years, only one woman has been hired as a tenure-track assistant professor in the basic science departments of Penn's medical school.</p>
<p class="img-with-caption"><img title="FIXING THE LEAKY PIPELINE" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/faculty.gif" alt="FIXING THE LEAKY PIPELINE"/></p>
<p>One widely acknowledged reason for the dearth of women in tenure-track assistant professor positions is that these high pressure jobs coincide with a woman's last best chance for children. Caring for a newborn child is a stress on both men and women, but according to a recent survey of NIH postdocs, women are more likely to make career concessions than men.</p>
<p class="img-with-caption"><img title="FIXING THE LEAKY PIPELINE" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/NIH.gif" alt="FIXING THE LEAKY PIPELINE"/></p>
<p>For starters 36% of men, compared to only 8% of women, have spouses who stay at home, giving men - as a group - an advantage in the workplace. When both partners work, the female cohort was still less likely to receive support at home. 31% of female respondents said they would make concessions for their husband's career, while only 21% of male respondents said they would. And 30% of men expected their wives to make concessions whereas only 15% of women had that expectation.</p>
<p>Recommendations: Follow the lead of some high-prestige research universities that have provided released time from teaching and administrative responsibilities for researchers who are primary caregivers - male and female. Unlike undergraduate departments, most basic science departments in medical schools have more faculty than are required for teaching their students. The institution also stands to gain, because grant funding is more apt to be maintained when junior faculty maintain momentum in research and publications.</p>
<p>This approach has been successful at the University of California, Berkeley, where 45% of tenure-track women take advantage of "reduced duties" policies.</p>
<p>When filling a faculty position, publicize the fact that your institution has family-friendly policies, and then actively recruit women rather than waiting for them to apply.</p>
<h4>The assistant professor to tenure leak</h4>
<p>Rearing children during the most demanding times in a scientist's career is just one of the issues women face. Many academic women don't have children. According to a UC, Berkeley-based survey of nearly 9,000 tenure track scientists across UC campuses, 48% of tenure track women did not have children. Clearly there are factors other than feelings of familial obligation that keep women from advancing in science.</p>
<p>Figure 2 reproduces NIH data showing that the proportion of K-series grants given to women has been steadily increasing over the years, and is now consistent with the proportion of women emerging from biomedical postdocs. Study section scores for women's R01 grant applications are now as high as or higher than men's. If women do make it to the stage of independent NIH-funded researcher, and are competing on the same level as men, then why do they comprise only 20% of senior faculty at prestigious medical schools?</p>
<p>Looking at statistics, a young woman might get the impression that her shot at the faculty positions at these schools would be difficult, if not out of reach.</p>
<p>While women have relatively high success rates for their first R01 applications, the story changes over the long run (see graph on p. 70). On their second, or renewal grants, women consistently have lower success rates than men. Part of the reason is that grant reviewers, like tenure committees, look at the number of publications as a major criterion of excellence. As one candid department chair explained it to a terminated assistant professor I know: "Quality is no substitute for quantity."</p>
<p>Women scientists, on average, do produce fewer publications than men (EMBO reports, 8:982-7, 2007). Why is that? Several answers have been suggested by the National Academies of Science 2007 report, "Beyond Bias and Barriers." One reason suggested in the report is that women, on average, devote more time to teaching and mentoring than men. Another is that women value advising students while men give greater emphasis to competition. The NAS report also suggests another possibility that has been largely ignored to date: that women have less access to the support systems and resources that increase faculty productivity.</p>
<p>In the world of biomedical research, good graduate students and postdocs are the hands and minds that can convert an excellent scientist into a highly productive scientist. They will drive the output of papers, contribute ideas and data leading to new research avenues, and markedly increase the overall productivity of the lab.</p>
<p>Successful graduate students and postdocs are savvy about what it takes to succeed in today's world of science. Both male and female graduate students perceive young women scientists as having less prestige, less clout, fewer contacts and less funding. The result is that women assistant professors are less likely to attract high quality graduate students and postdocs.</p>
<p>As far as money is concerned, those trainees would be right. As Charlotte Schubert reported in Nature Medicine (11:1129, 2005), for every funding dollar allocated to a research grant of a male principal investigator (PI), the average grant of a female PI provides 80 cents. This is, in part, because women are less likely to be PIs on NIH grants with larger dollar caps. Center grants with big budgets are consuming an increasing portion of the NIH budget, but less than 17% of center grants are awarded to women, compared to 24.5% of R awards (R01, R03, R21). As more and more funding dollars are shifted to large multi-investigator projects, the ability of women to gain parity in dollars per grant will no doubt decline further.</p>
<p>What's keeping search and award committees from thinking of the many highly-qualified female candidates? The data showing that women receive less money per grant and publish fewer papers contribute to the perception that young female scientists have less status and influence. The bottom line is a vicious cycle: less productivity yields fewer good students and postdocs, which yields less productivity. With less support at home, and less support in the lab, women have to work much harder to compete on the same playing field as men.</p>
<p>Recommendations: Organize high visibility activities featuring the accomplishments of junior women faculty to increase their status with graduate students. Seek out women faculty to be PIs on multi-investigator grants, center grants, and core facilities grants to boost parity. Then evaluate scientists for promotion based on the quality of research they produce - using citation rates, for example - rather than the number of publications and how much income they bring in. Some high prestige institutions assess the quality of their scientists' work by asking for, and reading, the 4-5 papers that the researchers identify as their most seminal work.</p>
<h4>The awards leak</h4>
<p>Once all of these challenges have reduced the availability pool, there is yet another considerable issue to overcome: the perception of excellence. The recent NAS report describes studies showing how the stereotype that women scientists are less prestigious is still prevalent.</p>
<p>What's keeping search and award committees from thinking of the many highly-qualified female candidates? Why do so few female scientists get awards like a Lasker or the Nobel for their contributions to science? The subtle bias described in the NAS report suggests that women do not fit the image both men and women have of prestige and leadership.</p>
<p class="img-with-caption"><img title="FIXING THE LEAKY PIPELINE" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/R01.jpg" alt="FIXING THE LEAKY PIPELINE"/></p>
<p>According to the Recognition of the Achievements of Women In Science, Medicine, and Engineering (RAISE) project's website, only 8.6% of Lasker Awards since 1991 have gone to female scientists. The RAISE project also reports that of the 474 awards they've counted, a full 33% have never gone to women.</p>
<p>Recommendations: I looked at the invited speakers at the Keystone symposia - one of the most well-regarded set of conferences in the life sciences - and tallied the number of invited speakers across 32 meetings encompassing seven fields. When a woman was present on the search committee the percentage of speakers who were women was 32%, while without any women among the organizers the percentage dropped to 25%, a statistically significant difference. Make sure all search committees for faculty positions as well as conferences contain a critical mass of women. Actively recruit women for leadership roles. Reconsider your personal definition of a driven and impressive scientist.</p>
<p>These are not the only solutions, but they're a start. Until academic science begins to address why top tier institutions have so few women among their biomedical faculty, young women are likely to find their prospects unsatisfactory and choose other options.</p>
<p>Phoebe Leboy is a professor of biochemistry emerita at the University of Pennsylvania, and the current president of the Association for Women in Science.</p>
