<h1>Initiatives</h1>
<h2>&nbsp;</h2>
<h3>Lilavati's Daughters</h3>
<p>This initiative of the Women in Science (WiS) Panel relates to mentoring of young women who are potentially looking for careers in science, engineering, medicine etc.<br /><a href="Lilavatis_Daughters">More ...</a></p><p>Check the <a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/brochure.pdf" target="_blank">brochure</a> to know what the book is all about.</p>
<p><a href="Lilavatis_Daughters#the_book">Daughters (The book)</a></p><hr />
<h3><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/surveyreport_web.pdf" target="_blank">Survey of trained scientific women power</a></h3>
<p>The Women in Science Panel (WiS) of Indian Academy of Sciences has initiated a study entitled 'Trained Scientific Woman Power: How Much are we losing and Why?'. This study aims to track down women who have completed their PhD in pure and applied sciences, engineering and medicine. A comparative study involving men PhD holders is also taken up to have an overall perspective on the situation of women scientists.<br /><a href="Survey_of_trained_scientific_women_power">More ...</a></p><hr />
<h3>Women in Science : A Career in Science</h3>
<p>The Panel of Women in Science has embarked on a new initiative of conducting a series of seminars/lectures on the topic "Women in Science : A Career in Science" under their Role Model Program. These seminars are conducted to address the various career options for women in the field of science. The seminars will have presentations by leading women scientists to showcase the work done by women scientists to an audience of both the genders.<br /><a href="A_Career_in_Science">More ...</a></p><hr />
<h3>To create a database of women scientists</h3>
<p>The Women in Science panel of Indian Academy of Sciences is creating a database of Indian women scientists. The database will help in the creation of a forum for women scientists, for exchange of thoughts and ideas regarding their status and roles as women in science. The same can also be used effectively in generating information which can be used for policy making.</p><p><a href="http://web-japps.ias.ac.in:8080/womensci/jsp/index.html" target="_blank">More ...</a></p><hr />
