<h1>INSA - AASAA joint workshop</h1>
<h2>&nbsp;</h2>
<h3>Presentations at the INSA-AASAA joint workshop on "Women in Science, Education and Research"</h3>
<p><strong>Date:</strong> 24 September 2013<br /><strong>Venue:</strong> New Delhi, India</p>
<ul class="list-unstyled gap-above">
	<li class="journal-article-list"><p><span>Doe Sun Na, The Korean Academy of Science and Technology, Korea</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Doe_Sun_Na.pdf" target="_blank">Women in Science: Current Status and Proposal</a></p></li>
	<li class="journal-article-list"><p><span>Jennifer Graves, Australian Academy of Science, Australia</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Balancing_Act.pdf" target="_blank">The Balancing Act</a></p></li>
	<li class="journal-article-list"><p><span>Farida Habibshaw, Vice President, OWSD, Malaysia</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Farida_Habib_Shah.pdf" target="_blank">Women in Leadership Roles in Science and Research: Plugging the Leaky Pipeline</a></p></li>
	<li class="journal-article-list"><p><span>Rohini M. Godbole, Indian Institute of Science, Bengaluru</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Rohini_M_Godbole.pdf" target="_blank">Gender Equity: Status, Goals and Strategies</a></p></li>
	<li class="journal-article-list"><p><span>Vinita Sharma, Department of Science and Technology, New Delhi</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Vinita_Sharma.pdf" target="_blank">DISHA: A Way Forward, Initiatives for Gender Parity in S &amp; T</a></p></li>
	<li class="journal-article-list"><p><span>Eun Hee Cho, Chosun University, Korea</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Eun_Hee_Cho.pdf" target="_blank">Searching for Women in Korean Scientific Societies</a></p></li>
	<li class="journal-article-list"><p><span>Shamima K Choudhury, University of Dhaka, Bangladesh</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Shamima_K_Choudhury.pdf" target="_blank">Challenges of Women in Science: Bangladesh Perspectives</a></p></li>
	<li class="journal-article-list"><p><span>Azra Khanum Member, PAS Council, Pakistan</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Azra_Khanum.pdf" target="_blank">An Overview of Pakistani Women in Education, Science and Research</a></p></li>
	<li class="journal-article-list"><p><span>Anjana Singh, Tribhuvan University, Nepal</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Anjana_Singh.pdf" target="_blank">Women in Science and Technology: Nepal's Experience</a></p></li>
	<li class="journal-article-list"><p><span>Mon-Shu Ho, National ChungHsing University, Nepal</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Mon_Shu_Ho.pdf" target="_blank">Developments for Taiwanese Women in Physics</a></p></li>
	<li class="journal-article-list"><p><span>Indira Chatterji, Universite d' Orleans, France</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Indira_Chatterji.pdf" target="_blank">Glass Ceiling and Leaky Pipeline in France</a></p></li>
	<li class="journal-article-list"><p><span>Jennifer A. Marshall Graves, Australian Academy of Science</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Jennifer_Graves.pdf" target="_blank">Women Scientists in Australia - facts and figures</a></p></li>
	<li class="journal-article-list"><p><span>Hayrunnisa Bolay Belen, Gazi University Ankara Turkey, Turkey</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Hayrunnisa_B_Belen.pdf" target="_blank">Women in Science &amp; Education in Turkey</a></p></li>
	<li class="journal-article-list"><p><span>Eun Hee Cho, Chosun University, Korea</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Best_Practices.pdf" target="_blank">Best Practices for Gender Equality in Science</a></p></li>
	<li class="journal-article-list"><p><span>Ram Ramaswamy, University of Hyderabad, Hyderabad</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Ramakrishna_Ramaswamy.pdf" target="_blank">A Fine Balance: Women in Science Navigating Academia</a></p></li>
	<li class="journal-article-list"><p><span>Manju Sharma, Distinguished Woman Scientist Chair, NASI</span></p><p><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Manju_Sharma.pdf" target="_blank">Scientific and Technological Empowerment of Women -  Role, Relevance and Application</a></p></li>
</ul>
