<h1>Journals and Conferences</h1>
<h2>&nbsp;</h2>
<h3>Articles from Journals and Conferences</h3>
<br />
<ol>
	<li class="journal-article-list"><a href="http://www.nature.com/naturejobs/science/articles/10.1038/nj0406" target="_blank">"For she's a jolly good fellow"</a> - An article published in Nature about 'women in science'.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/APS_News.pdf" target="_blank">An article on Emmy Noether (a significant mathematician)  published in APSNews.</a></li>
	<li class="journal-article-list"><a href="http://pss.sagepub.com/content/early/2013/03/18/0956797612458937.abstract" target="_blank">"Not lack of ability but more choice - Individual and gender differences in choice of careers in science, technology, engineering and mathematics"</a></li>
	<li class="journal-article-list"><a href="http://sciencecareers.sciencemag.org/career_magazine/previous_issues/articles/2010_08_06/caredit.a1000077" target="_blank">Scientist Dads Step up</a><br />Science magazine Although women still do most of the parenting, some scientist dads are taking on the role of primary caregiver.</li>
	<li class="journal-article-list">Few interesting articles on gender issues in biomedical research and women in science in the journal <a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Nature.pdf" target="_blank">Nature</a>.</li>
	<li class="journal-article-list"><a href="http://sciencecareers.sciencemag.org/career_magazine/previous_issues/articles/2010_06_04/caredit.a1000056" target="_blank">Time to hire a housekeeper?</a><br />Science magazine An article on Women in Science which talks about the concept of hiring help by women scientists to manage their housework so that their research activities are not disturbed.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/whysofew.pdf" target="_blank">Why so few?</a><br />A report by the American Association of University Women (AAUW) on the study of women's under representation in science, technology, engineering and mathematics.</li>
	<li class="journal-article-list"><a href="http://www.nytimes.com/2010/03/22/science/22women.html?_r=1&amp;emc=eta1" target="_blank">Bias Called Persistent Hurdle for Women in Sciences</a><br /> An article in the New York Times about the AAUW report "Why so few?"</li>
	<li class="journal-article-list"><a href="http://nanopolitan.blogspot.in/2009/11/lilavatis-european-daughters.html" target="_blank">Lilavati's European Daughters</a><br /> A blog about a book titled 'Women in Science' brought out by the European Commission featuring the life stories of European women scientists over the centuries. (Check the book Women in Science)</li>
	<li class="journal-article-list"><a href="http://web.stanford.edu/dept/HPST/schiebinger.html" target="_blank">Gendered Innovations in Science and Engineering; Nature's Body: Gender in the Making of Modern Science; Has Feminism Changed Science?; The Mind has no Sex? Women in the origins of Modern Science</a><br /> These are some of the interesting and well known publications of Prof. Londa Schiebinger (Professor of History of Science and Director, Clayman Institute for Gender Research, Stanford University), which deal with women in science and engineering, and gender issues in science, medicine and engieering.</li>
	<li class="journal-article-list"><a href="http://www.symmetrymagazine.org/article/july-2009/growing-a-diverse-workforce" target="_blank">Growing a diverse workforce</a><br /> An article in the magazine 'Symmetry', a joint Fermilab/SLAC publication, which talks about the efforts taken by the three National Labs of USA - Fermilab, SLAC and Brookhaven, to train, hire and retain women and members of ethnic minorities in the field of Particle Physics.</li>
	<li class="journal-article-list"><a href="http://sciencecareers.sciencemag.org/pdf/tools_tips/outreach/loreal_wis_2009/loreal_wis_2009.pdf" target="_blank">Young Women in Science</a><br /> A L'Oréal-UNESCO Women in Science booklet The booklet contains profiles of young women who are at the start of their science careers, who tell their stories of passion and persistence - what drives and excites them about their work in the sciences.</li>
	<li class="journal-article-list"><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/MothersinScience.pdf" target="_blank">Mothers in Science: 64 ways to have it all</a><br />A book by Royal Society. This book is brought out as part of the project of the 2007 Rosalind Franklin Award winner Prof. Ottolene Leyser. The book contains the professional and personal time lines of 64 senior ranking female scientists working in STEM (Stimulating the interests of young people in Science, Technology, Engineering and Mathematics).</li>
	<li class="journal-article-list"><a href="http://portal.ictp.it/pio/numbers/WomenPoster.jpg" target="_blank">Women Scientists at ICTP</a><br /> This poster gives an overview of women scientists at the International Centre for Theoretical Physics (ICTP).</li>
	<li class="journal-article-list"><a href="http://genderandset.open.ac.uk/index.php/genderandset" target="_blank">International Journal of Gender, Science and Technology</a><br /> This is a peer-reviewed open access journal which focuses on gender issues in and of science and technology, including engineering, construction and the built environment, and aims to explore the intersections of policy, practice and research.</li>
</ol>
<h3><a href="Archives">Archives</a></h3>
