<h1>Plan of Action</h1>
<h2>&nbsp;</h2>
<p>The following is the summary of the discussions that took place in a meeting of the Committee of the Indian Academy of Sciences for 'Women in Science' and action plans that were identified at this meeting:</p>
<ol>
	<li class="gap-above-small">A database of women in sciences at all levels needs to be created. This should be a repository of information for and of women in Science. To avoid duplication of a similar effort being undertaken by INSA, we should work closely with INSA to this end.</li>
	<li class="gap-above-small">A report on the status of "Women in Science in India", containing hard facts and figures, is essential while addressing the issue of 'Women in Science'. However, implementation of specific action plans to increase participation of Women in Indian Science, at all levels, need not wait for the completion of such a report. The report is getting ready by a committee appointed by INSA towards this purpose.</li>
	<li class="gap-above-small">A web page for "Women in Science", as part of the Academy website, should be designed. This should summarize the aims of the working committee and the initiatives it plans to undertake. This page could serve the role of being a repository mentioned under point 1 once it is developed. Similarly, an article discussing the issues involved to increase the awareness of the Scientific Community to these issues, in "Current Science" is being planned. Perhaps a special issue of Current Science with articles from scientists as well as social scientists analyzing the issues can be considered.</li>
	<li class="gap-above-small">Experts from diverse fields such as social scientists and psychologists to be involved in the discussion of the working group. Reports brought out by other agencies (such as IUPAP) could be useful for work of this working Committee.</li>
	<li class="gap-above-small">For a while a session on "Women in Science" should become a regular feature of the Academy's Mid-Year and Annual Meetings and should be a part of the mainstream activity.</li>
	<li class="gap-above-small">It was planned to organize an informal meeting, moderated by Indira Nath, at the forthcoming Guwahati Annual Meeting, which included participants of the Annual meeting of the Academy, the faculty of IIT, Guwahati, the University, Assam Science Society etc. The participants necessarily involved women but were not be limited to them.</li>
	<li class="gap-above-small">A role model programme named after some of the famous women fellows of the Academy should be started by the Academy. This will invlove special lectures, mentoring etc., similar to the activities of the Educational Panel of the Academy. In addition one could think of holding special workshops fo girl students, for example, laboratory training, training in mathematics etc.</li>
	<li class="gap-above-small">Books and reading material which give biographical sketches of eminent Indian women scientists and teachers should be brought out by the Academy. Plans for doing this on have been formulated.</li>
	<li class="gap-above-small">A Workshop on Women in Science can held next summer to discuss the basic issues. This should include social scientists and women and men scientists. This could culminate in a national meeting later.</li>
	<li class="gap-above-small">Funding support for organizing the various programmes of the Working Group could be sought from the Central and State Women Welfare Ministries.</li>
	<li class="gap-above-small">Proactive steps need be taken to increase the number of women fellows of the Academy, to remedy the current inadequate representation in the Fellowship of the active women scientists in the country. Representation of Women in the Academy committees (Sectional Committees, Editorial Boards etc.,.) needs to be increased proactively.</li>
	<li class="gap-above-small">The committee will enlarge its present composition to include additional members in order to execute many of the things that are being planned.</li>
	<li class="gap-above-small">The committee should bring to the notice of the Fellows some of the recruitment policies which are counter-productive to the development of the career of women scientists, as many of the Fellows of the Academy are involved in the hiring process. The issues mentioned (which also arose in the discussions in Gauhati) were:
		<ol>
			<li class="gap-above-small">Giving due weightage to possible breaks in the professional careers taken  by Women Scientists for starting a family, i.e, consider 'Academic Age' while performing evaluation.</li>
			<li class="gap-above-small">Being alive to the problem of dual careers. i.e., job opportunities should not be ruled 'out of hand' by unwritten, artificial restriction of no jobs for a couple in the same Institute. All the IIT's seem to implement something like this.</li>
		</ol>
	</li>
	<li class="gap-above-small">Fellows of the academies are also involved in policy making. They should try to initiate women friendly practices such as having a crèche, giving priority to women for On Campus Housing etc.</li>
</ol>
