<h1>Survey of trained scientific women power</h1>
<h2>&nbsp;</h2>
<p>The Women in Science Panel (WiS) of Indian Academy of Sciences has initiated a study entitled 'Trained Scientific Woman Power: How Much are we losing and Why?'. This study aims to track down women who have completed their PhD in pure and applied sciences, engineering and medicine.</p>
<p>It has been observed that although several women students are sufficiently motivated to continue their scientific education up to their Phd. degree but their post-PhD. remain disproportionately low. The reasons have been documented to some extent, but not analysed.</p>
<p>The Panel for Women in Science (WiS) of the Indian Academy of Sciences has initiated a project to identify the factors involved in the choice of women with a Ph.D to leave the pursuit of science. This survey is being conducted by a group consisting of women scientists such as Drs. B.K. Anitha, Vineeta Bal, Rohini Godbole, Shobona Sharma and Pratima Sinha. Social scientists Drs. Karuna Chanana(JNU) and N.S Anuradha(IISc) are also participating in the project.</p>
<p>For the survey, it is important to interview women who are continuing in a scientific career as well as those who are not. We are therefore compiling a database of women with a Ph.D. degree in Science, Engineering or Medicine.</p>
<p>Primarily, we hope that the survey will help us to compile the data of women scientists in India from various sectors mentioned above and find possible reasons for the small number of women scientists in research.</p>
<p>The issue of Current Science (25th August, 2007) contains an <a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/scientific_women_power.pdf" target="_blank">appeal</a> to all women who fall within the scope of the database to register. If you should fall within the scope of this database follow the instructions given in the advertisement to <a href="http://web-japps.ias.ac.in:8080/womensci/jsp/index.html" target="_blank">register</a>. Currently the number of women who have registered with our database stands at 2295. Click here to view the list of <a href="http://111.93.135.170:8080/womensci/jsp/ListForGuest.jsp" target="_blank">registered members</a>.</p>
<p>To be effective such a study needs to be comparative so as to gain an overall perspective on the situation of women scientists vis-a-vis men scientists. Therefore, we intend to include men scientists for a holistic view of the situation. For this purpose, we invite the participation of Men Scientists in the study.</p>
<p>As part of the study, we <a href="http://203.197.183.69:8080/mensci/jsp/index.html" target="_blank">appeal</a> to all the men scientists with a doctoral degree in science, engineering or medicine, irrespective of whether they may be pursuing an academic or scientific career to <a href="http://www.ias.ac.in/womeninscience/menscientists/" target="_blank">register</a> with our database by following the instructions given in the appeal. Currently the number of men who have registered with our database stands at 405. Click here to view the list of <a href="http://203.197.183.69:8080/mensci/jsp/ListForGuest.jsp" target="_blank">registered members</a>.</p>
<p>We expect the study will give us a comprehensive view of factors responsible for the loss of women scientists in our country. We urge you to help us in this endeavour.</p>
<h4><a href="http://indianwomenscientists.in/" target="_blank">DST Task Force on Women in Science</a></h4>
<p>The DST Task Force on Women in Science is maintaining a directory of Indian women who have taken up studies in Science/Agriculture, Engineering and Medicine. The directory provides a resource pool of Women Scientists, Engineers and Doctors who have registered with them. The registrants are not necessarily Ph.D holders and are also those who are pursuing Ph.Ds.</p>
<h4><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/taskforce_report.pdf" target="_blank">Evaluating and Enhancing Women's Participation in Scientific and Technological Research: The Indian Initiatives</a> – A report of National Task Force for Women in Science, DST.</h4>
<h4><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/Recommendations_NASI.pdf" target="_blank">M. Sharma and K. Mishra, Eds., "Role of Women Scientists and Teachers in promotion and application of Science &amp; Technology: Easing the Drudgery of Women", (2013)</a></h4>
<p>Women are universally under-represented in science and technology; may be, because they have seen few role models of their gender in such establishment. However, Lilavati's Daughters: The Women Scientists of India, is an eye-opening collection of essays of nearly 100 Indian women scientists from the Victorian era to present-day India, giving inspiring accounts of what brought them to science and what kept them going despite the exorbitant social and personal dues they paid along the way. But, simply writing such a treasure can not make any phenomenal change in the miseries of women, especially those, who have attained knowledge and wisdom, but are still lagging behind in the pursuit of science for the development of society in general and their socio-economic wellness, in particular. Realizing this very fact as well as recognizing the substantial role of women scientists and teachers in providing support and solution, and most importantly, in pursuit of its mandate of "Science &amp; Society", the National Academy of Sciences, India (NASI), launched a nationwide program on "Technological Empowerment of Women" during the year 2012-2013 under overall supervision and convenership of Prof. (Mrs.) Manju Sharma, NASI Distinguished Woman Scientist Chair &amp; formerly Secretary to the Government of India, along with other distinguished scientists Prof. Krishna Misra, Prof. Paramjeet Khurana, Prof. Kasturi Datta and Prof. Veena Tandon with the approval of the Council of the Academy (NASI) for organizing the series of workshops in different regions of the country on "Defining Role of Women Scientists and Teachers in Promotion and Application of Science and Technology". NASI organized several workshops under this programme in different places covering different regions of the country; and after this vigorous exercise, the recommendations (Appendix-I) of these workshops were published and discussed on various platforms.</p>
<h3>RELATED NEWS</h3>
<h4><a href="http://timesofindia.indiatimes.com/city/bengaluru/Supermoms-put-in-40-hrs-on-research/articleshow/7300298.cms?" target="_blank">'Supermoms put in 40 hrs on research'</a></h4>
<p>An article in Times of India about the report of the study 'Trained scientific women power: How much are we losing and why?' conducted by WiS Panel of IASc.</p>
<h4><a href="http://www.thehindu.com/todays-paper/tp-national/tp-karnataka/article762528.ece" target="_blank">"Women scientists face systemic biases"</a></h4>
<p>An article in The Hindu about the report of the study 'Trained scientific women power: How much are we losing and why?' by the WiS Panel of the Academy.</p>
<h4><a href="<?=RESOURCES_URL?>Initiatives/Women_in_Science/surveyreport_web.pdf" target="_blank">"Trained Scientific Women Power: How Much are we Losing and Why?"</a></h4>
<p>The report of the study conducted by the WiS Panel of Indian Academy of Sciences is released!</p>
