<h1>Turing Award for a great woman explorer and a champion of women in science</h1>
<h2>BusinessWeek, 23 February 2007</h2>
<p>The Turing Award Honors Frances Allen The first woman to receive the nation's top science prize pioneered program optimization—and IBM's product development process by <a href="http://www.businessweek.com/bios/Steve_Hamm.htm" target="_blank">Steve Hamm</a></p>
<p>How does it feel to be the first woman to receive the nation's top computer science award? Sweet, indeed, says Frances Allen, the IBM Fellow Emerita who this week received the prestigious A.M. Turing Award. "I have worked hard for women to be recognized, and I'll use this as a platform to get more attention to the role of woman in computing", she says.</p>
<p>The Association for Computing Machinery cited Allen, 74, for her pioneering contributions to the "theory and practice of optimizing compiler techniques". For the layperson, that means she came up with techniques for writing software programs for supercomputers that saved programming time and made it easier to take on complex problems in drug discovery, genomic research, and climate mapping. "The Turing Award recognizes deep technical contributions that have a lasting impact. That's certainly the case in the work that Fran did", says John White, the chief executive of ACM. He says a woman getting the award is "long overdue".</p>
<h3>Championing Women in Science</h3>
<p>One of the ACM's goals is to encourage more women to get into the computer science field. Right now, only 26% of the workers in America's information technology industry are women, and that's down from 33% in 1990. The ratio seems likely to decline even further in future years. These days, only about 15% of undergraduate computer science degrees at major universities go to women.</p>
<p>Allen is working hard to reverse the trend. Since she retired from IBM Research in 2002 after a 45-year career, she has spent much of her time working within professional organizations to increase the role of women in computing. "It's essential for women to participate", she says. "A diversity of people can bring a much more creative environment and better results".</p>
<p>The Turing Award is named for Alan Mathison Turing, a 20th century English mathematician and cryptographer who is considered by many to be the father of modern computer science. Notable previous award winners include Internet pioneer Vinton G. Cerf, computer mouse inventor Douglas Engelbart, and artificial intelligence innovator Marvin Minsky. Microsoft researcher Jim Gray, another Turing Award winner (who was lost at sea while sailing alone off the California coast in January) was on the committee that selected Allen. The award program, which was started in 1966, includes a $100,000 prize.</p>
<p>Leaders in the computer science field reacted positively to Allen's award. "This is really the Nobel prize of computing", says William Wulf, president of the National Academy of Engineering in Washington, D.C., who has known Allen since the early 1970s. Back in those days, a debate raged in the computer science community over whether it was better to write programs for each type of mainframe or minicomputer using so-called machine languages, or whether higher-level languages such as Fortran would be more effective. With the higher-level languages, much less programming would be required. Allen argued for using those languages and translating them into machine languages using compiler programs. She came up with techniques for optimizing compilers so they would operate quickly and with relatively few bugs. Ultimately, her side won the debate. Now, most computer programs are written in languages such as C and Java, and programs can easily be adapted to run on different kinds of computers.</p>
<h3>Innovating Science and an IBM Process</h3>
<p>It's a very different path than Allen started off on 50 years ago. Intending to teach school, she got a degree in education from Albany State Teacher's College and an MA in math from the University of Michigan. But then she joined IBM in 1957 to pay off her student loans and began her decades-long association with a research organization that routinely gets more U.S. patents than any other research organization. Even in those early days, Allen would invent new science in the labs, participate in developing new products based on it, and work with customers to make sure they were able to get full value from the products. In one case, she spent a year with a customer while new computers based on her ideas were deployed there.</p>
<p>In recent years, the practice of exposing researchers to customers has become a full-blown strategy at IBM. Researchers are expected to get involved in product development and also, with increasing frequency, to work directly with customers on some of their most difficult problems. The company credits Allen with helping to get that started. "She's really the mother of customer-oriented computing", says Robert Morris, IBM's vice-president for services research. "She was an early proponent and practitioner of what has become our innovation model. There was a time when we thought of innovation as being just associated with invention. Now we see it as a path from the invention through to where it has an impact on how people live their lives".</p>
<p>Allen retired from IBM four years ago so "I could do whatever I wanted, whenever I wanted". That includes climbing mountains, a passion since the 1970s. Back then, she participated in six first-ascents of mountains in the arctic—trips with no maps and no radio contact. Her interest in climbing continues. Last April, she and three companions climbed a 14,000-foot peak in the Himalayas. There's a strong parallel between research and climbing: "I love working on new ideas and new possibilities", she says. "I'm an explorer in just about every sense".</p>
<p>Hamm (steve_hamm@businessweek.com) is a senior writer for *BusinessWeek* in New York.</p>
