<h1>Women Young Scientists of INSA</h1>
<h2>INSA - Indian National Science Academy</h2>
<h4>Dr Rehna Augustine</h4><p>National Institute of Plant Genome Research, New Delhi<br /><strong>Year of Award:</strong> 2015</p><hr />
<h4>Dr Tanvi Jain</h4><p>Indian Statistical Institute, New Delhi<br /><strong>Year of Award:</strong> 2015</p><hr />
<h4>Dr Sameena Khan</h4><p>Translational Health Science and Technology Institute, Faridabad<br /><strong>Year of Award:</strong> 2015</p><hr />
<h4>Dr Hima Bindu Kudapa</h4><p>Center of Excellence in Genomics,  International Crops Research Institute for the Semi - Arid Tropics, Greater  Hyderabad<br /><strong>Year of Award:</strong> 2015</p><hr />
<h4>Dr Upasana Ray</h4><p>National Cancer Institute, National Institutes of Health, Bethesda, USA.<br /><strong>Year of Award:</strong> 2015</p><hr />
<h4>Dr. Gayathri Pananghat</h4><p>Indian Institute of Science Education and Research, Pune 411 021<br /><strong>Specialization:</strong> Structure and mechanism of cytoskeletal motility systems<br /><strong>Year of Award:</strong> 2014</p><hr />
<h4>Dr. Mahalakshmi Radhakrishnan</h4><p>Indian Institute of Science Education and Research, Bhopal, Pune 411 021<br /><strong>Specialization:</strong> Structure and mechanism of cytoskeletal motility systems<br /><strong>Year of Award:</strong> 2014</p><hr />
<h4>Dr. Ranjani Viswanatha</h4><p>Jawaharlal Nehru Centre for Advanced Scientific Research, Bengaluru 560064<br /><strong>Specialization:</strong> Nanomaterials, Spectroscopy and Electronic Structure, Magnetism<br /><strong>Year of Award:</strong> 2014</p><hr />
<h4>Dr. Rohini Garg</h4><p>National Institute of Immunology, New Delhi 110 167<br /><strong>Specialization:</strong> Cell Biology<br /><strong>Year of Award:</strong> 2014</p><hr />
<h4>Dr. Abha Misra</h4><p>Indian Institute of Science, Bengaluru 560 012<br /><strong>Specialization:</strong> Graphene and CNT-based NEMS/MEMS Devices, Sensors and Actuators, Hybrid Fuel Cells<br /><strong>Year of Award:</strong> 2013</p><hr />
<h4>Dr. Pavithra Lakshminarasimhan Chavali</h4><p>University of Cambridge, Cambridge, U K<br /><strong>Specialization:</strong> Molecular Biology of Rice Seed Development<br /><strong>Year of Award:</strong> 2013</p><hr />
<h4>Dr. Shiny Narayanankutty Nair</h4><p>Yale Cancer Centre, Connecticut, USA<br /><strong>Year of Award:</strong> 2013</p><hr />
<h4>Dr. Sonali Sengupta</h4><p>Bose Institute, Kolkata 700 054<br /><strong>Specialization:</strong> Inositol Metabolism<br /><strong>Year of Award:</strong> 2013</p><hr />
<h4>Dr. Pinky Agarwal</h4><p>National Institute of Plant Genome Research, New Delhi 110 067<br /><strong>Specialization:</strong> Molecular Biology of Rice Seed Development<br /><strong>Year of Award:</strong> 2012</p><hr />
<h4>Dr. Suman Dasgupta</h4><p>CSIR Nort-East Institute of Science and Technology, Jorhat 785 006<br /><strong>Year of Award:</strong> 2012</p><hr />
<h4>Dr. Moushami Mallik</h4><p>Max Planck Institute for Molocular Biomedicine, Muenster, Germany<br /><strong>Year of Award:</strong> 2012</p><hr />
<h4>Dr. Supriya Tiwari</h4><p>S.S.S.V.S. Government PG College, Chunar, Mirzapur, Uttar Pradesh<br /><strong>Year of Award:</strong> 2012</p><hr />
<h4>Dr. Moumita Chaki</h4><p>University of Michigan, Michigan 48109, USA<br /><strong>Specialization:</strong> Molecular Biology, Mendelian Disorders, Genetics and Vision Science.<br /><strong>Year of Award:</strong> 2011</p><hr />
<h4>Dr. Sharmistha Dutta Choudhury</h4><p>Bhabha Atomic Research Centre, Mumbai 400 085<br /><strong>Year of Award:</strong> 2011</p><hr />
<h4>Dr. Lekha Divya</h4><p>University of Kerala, Kariavattom, Thiruvananthapuram 695 037<br /><strong>Year of Award:</strong> 2011</p><hr />
<h4>Dr. Gitanjali Yadav</h4><p>National Institute of Plant Genome Research, New Delhi 110 067<br /><strong>Specialization:</strong> Isoprinoid Mediated Responses in Plants<br /><strong>Year of Award:</strong> 2011</p><hr />
<h4>Dr. Kanika Bajaj</h4><p>University of California, Berkeley, CA<br /><strong>Year of Award:</strong> 2010</p><hr />
<h4>Dr. Niti Kumar</h4><p>Max Planck Institute of Biochemistry, Munich Area, Germany<br /><strong>Year of Award:</strong> 2010</p><hr />
<h4>Dr. Yamuna Devi Paila</h4><p>University of Massachusetts<br /><strong>Year of Award:</strong> 2010</p><hr />
<h4>Dr. Anindita Bhadra</h4><p>Centre for Ecological Sciences, Indian Institute of Science, Bengaluru 560 012<br /><strong>Specialization:</strong> Ecological Sciences (Eusocial wasp)<br /><strong>Year of Award:</strong> 2009</p><hr />
<h4>Dr. KV Brinda</h4><p>Post Doctoral Fellow, Department of Computer Science, Cornell University, Ithaca, NY 14853-7501<br /><strong>Specialization:</strong> Computer Science and Bioinformatics<br /><strong>Year of Award:</strong> 2009</p><hr />
<h4>Dr. Archana Sunil Gandhe</h4><p>Laboratory of Molecular Genetics, Centre for DNA Fingerprinting and Diagnostics (CDFD), Hyderabad 500 001<br />Email: archana.gandhe@gmail.com<br /><strong>Specialization:</strong> Molecular Genetics<br /><strong>Year of Award:</strong> 2009</p><hr />
<h4>Dr. Yamuna Krishnan</h4><p>Fellow E<br /> National Centre for Biological Sciences, TIFR, UAS-GKVK Campus, Bengaluru<br />Email: yamuna@ncbs.res.in<br /><strong>Specialization:</strong> Chemical Biology of Nucleic Acids<br /><strong>Year of Award:</strong> 2009</p><hr />
<h4>Dr. Beena R Pillai</h4><p>Scientist<br />Comparative Genomics and Gene Expression, Institute of Genomics and Integrative Biology, Delhi 110 037<br />Email: beena@igib.in<br /><strong>Specialization:</strong> Gene Expression<br /><strong>Year of Award:</strong> 2009</p><hr />
<h4>Dr. Sangita Bose</h4><p>Guest Scientist<br />Max Planck Institute for Solid State Research, Nanoscale Science Department, Heisenberg Strasse 1 D 70569, Stuttgart, Germany<br />E-mail: sangita.bose@fkf.mpg.de; sangita.bose@gmail.com<br />Telephone: +49-711-6891638, 1728<br /><strong>Specialization:</strong> Experimental Condensed Matter Physics<br /><strong>Year of Award:</strong> 2008</p><hr />
<h4>Dr. T Kavitha</h4><p>Assistant Professor<br /> CSA Department<br /> Indian Institute of Science, Bengaluru 560 012<br />E-mail: kavitha.telikepalli@gmail.com; kavitha@csa.iisc.ernet.in<br />Telephone: 080-2293 2239<br /><strong>Specialization:</strong> Computer Science (Algorithms and Complexity)<br /><strong>Year of Award:</strong> 2008</p><hr />
<h4>Dr. Rohini Qamra</h4><p>31 River Court, Apt 3407, Jersey City, NJ 07310, USA<br />E-mail: rohiniq@gmail.com<br /> Telephone: +1-201-526-3793<br /><strong>Specialization:</strong> Biochemistry and Structural Biology<br /><strong>Year of Award:</strong> 2008</p><hr />
<h4>Dr. Sharmistha Sinha</h4><p>Post Doctoral Scholar<br />Department of Neurology(RNo 455), David Geffen School of Medicine, University of California, 635 Charles E Young Drive South Los Angeles, CA 90095, USA<br />E-mail: sinhas@ucla.edu<br /><strong>Specialization:</strong> Biophysical Chemistry and Glycobiology<br /><strong>Year of Award:</strong> 2008</p><hr />
