<h1>Role of the Academy</h1>
<h2>Prepared in 1975 by a committee appointed by the President and approved by the President in Council.</h2>

<p>Science has emerged today as the most revolutionary co-operative activity of mankind. In the scientific method lies a validity and universality which transcends any other principle devised by man. Science seeks and discovers, cutting across sectarian, national and ideological frontiers. It fosters co-operation and generates a value system which nurtures man’s highest capabilities and aspirations.</p>
<p>The Indian Academy of Sciences, founded in 1934 by Professor C.V. Raman, Nobel Laureate, endeavours by all means at its disposal to promote the progress and uphold the cause of science, both in pure and applied branches. The Academy has laid the responsibility on all its Fellows, individually and collectively, of promoting original research and of disseminating scientific knowledge to the community, through its activities of organizing meetings, discussions, seminars, symposia and publications. The Academy recognizes the special relationship of scientific creative activity with the process of education and holds that the course of discovery includes the identification and nurturing of scientific talent amongst the young. Aware of the fundamental contributions science and technology can and must make to national regeneration, the Academy upholds that the principle of social responsibility for all scientific effort, individual or corporate, is entirely consistent with individual freedom and that the quest for knowledge and truth cannot be reconciled with any dogma.</p>
<p>In order to meet the needs of the times, the Council of the Academy has carefully considered the steps to be taken to further the objects of the Academy. Taking cognizance of the enormous and continuing increase in scientific knowledge and the application of this knowledge virtually to every sphere of human activity, and considering the growth of scientific activity within India and the numbers of scientific institutions and scientists working in various fields, the Council has, as a first step, expanded the Fellowship, in order to have within the Academy a fuller representation of the Indian scientific community in its corporate body so that the objectives and obligations of the Academy could be more effectively fulfilled. The other steps proposed are aimed at:</p>
<ul>
	<li>ensuring that there is full representation in the Academy of all branches of science, fundamental and applied;</li>
	<li>placing special emphasis on bringing into the fold of the Academy, through election to the Fellowship, outstanding young scientists;</li>
	<li>promoting high quality journals in order to provide publication opportunities to Indian scientists at the international level;</li>
	<li>conducting symposia and seminars and encouraging other similar activities in order to provide means of exchange of scientific knowledge among scientists and to bring new knowledge to the attention of the whole scientific community;</li>
	<li>recognizing further, and honouring excellence in various areas of science by the institution of special awards (in the form of medals, lectureships, etc.);</li>
	<li>giving special encouragement to young scientists by the award of scholarships and fellowships to enable them to pursue their particular interests;</li>
	<li>promoting international understanding in science through the institution of special chairs and professorships, which will allow scientists from abroad to visit India for specific periods and provide means for travel for Indian scientists to visit other countries;</li>
	<li>taking up integrated studies in specific fields where co-ordinated scientific activities tend to be neglected.</li>
</ul>
<p>The Academy affirms that the rightful place for science and the men who rigorously cultivate it can be assured in society primarily through their devotion to the principles of objectivity, integrity and freedom from dogmas rather than through any formal processes of recognition. Not unmindful of the crucial role the Academy can play in national regeneration, the Academy adheres to the belief that this ideal would be best served by preserving the independence of the Academy from all official, State or Organization-related channels.</p>
<p>In a situation where almost every facet of life needs to be revitalized retaining a clear perspective for the nurturing of the scientific temper is of the utmost importance. In a country beset with prejudices, rules and bureaucratic formalisms, it is of the greatest value that working scientists, specially Fellows of the Academy, promote by personal as well as collective example, the principle of rational thought of function and relevance, rather than precedents. By applying rigorous standards of scientific criticism at all levels in a constructive sense, the Academy considers that the scientific community has a unique contribution to make not only to the flowering of science in India but also to national character.</p>
