<h1>Refresher Courses</h1>
<h2>Following refresher courses were held at various locations.</h2>

<p>This is an all India programme to help teachers improve their background knowledge and teaching skills. The duration is two weeks and approximately 30 teachers undergo a rigorous course of lectures, discussions and problem-solving sessions. The Academy meets the train fare and full boarding and lodging expenses of all participants. A list of the refreshers courses so far held and planned appears elsewhere.</p>
<h4>2015-02-10 to 2015-02-25</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Materials preparation and measurement of properties IV<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2015-01-20 to 2015-01-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> Tezpur University, Tezpur</p><hr />
<h4>2015-01-12 to 2015-01-25</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Advances in chemical sciences and sustainable development<br /><strong>Address:</strong> Central University of Rajasthan, Ajmer</p><hr />
<h4>2015-01-06 to 2015-01-22</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXVII<br /><strong>Address:</strong> Central University of Karnataka, Gulbarga</p><hr />
<h4>2014-12-26 to 2015-01-09</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Crystallography, mineralogy, igneous petrology and thermodynamics<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2014-12-20 to 2015-01-02</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Foundations of physics<br /><strong>Address:</strong> Indian Women Scientists Association, Navi Mumbai</p><hr />
<h4>2014-12-10 to 2014-12-25</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXVI<br /><strong>Address:</strong> S. M. V. D. University, Katra</p><hr />
<h4>2014-12-08 to 2014-12-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Classical mechanics and electromagnetism<br /><strong>Address:</strong> S. D. M. College, Ujire</p><hr />
<h4>2014-12-08 to 2014-12-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Application of quantum mechanics to atoms, moleculea and radiation<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2014-12-02 to 2014-12-17</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Materials preparation and measurement of properties III<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2014-11-11 to 2014-11-26</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXV<br /><strong>Address:</strong> Vidya Vikas Institute of Engineering and Technology, Mysore</p><hr />
<h4>2014-11-11 to 2014-11-26</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXIV<br /><strong>Address:</strong> Goa University, Goa</p><hr />
<h4>2014-10-08 to 2014-10-21</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Designing experimental projects in physics<br /><strong>Address:</strong> Midnapore College, Medinipur</p><hr />
<h4>2014-10-07 to 2014-10-22</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXIII<br /><strong>Address:</strong> Sri Krishnadevaraya University, Anantapur</p><hr />
<h4>2014-09-09 to 2014-09-26</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Materials preparation and measurement of properties II<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2014-07-08 to 2014-07-23</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXII<br /><strong>Address:</strong> Indian Institute of Science Education and Research, Mohali</p><hr />
<h4>2014-06-16 to 2014-07-01</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LXI<br /><strong>Address:</strong> Amrita Vishwa Vidyapeetham, Kollam</p><hr />
<h4>2014-06-03 to 2014-06-18</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LX<br /><strong>Address:</strong> Department of Atomic Energy Centre for Basic Sciences, University of Mumbai, Mumbai</p><hr />
<h4>2014-05-27 to 2014-06-11</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LIX<br /><strong>Address:</strong> Government College, Rajahmundry</p><hr />
<h4>2014-05-12 to 2014-05-27</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LVIII<br /><strong>Address:</strong> Goa University, Goa</p><hr />
<h4>2014-05-06 to 2014-05-21</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Materials preparation and measurement of properties I<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2014-05-05 to 2014-05-18</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Quantum mechanics<br /><strong>Address:</strong> Bishop Moore College, Mavellikara</p><hr />
<h4>2014-05-05 to 2014-05-17</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Bioinformatics in modern biology<br /><strong>Address:</strong> Manipal University, Manipal</p><hr />
<h4>2014-03-18 to 2014-04-02</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LVII<br /><strong>Address:</strong> P. D. Patel Institute of Applied Sciences, Changa</p><hr />
<h4>2014-03-10 to 2014-03-22</h4><p><strong>Subject:</strong> Engineering<br /><strong>Title:</strong> Recent trends in computer science and engineering: refreshing young minds<br /><strong>Address:</strong> Guru Nanak Dev Engineering College, Bidar</p><hr />
<h4>2014-02-11 to 2014-02-26</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LVI<br /><strong>Address:</strong> Panjab University, Chandigarh</p><hr />
<h4>2014-01-09 to 2014-01-25</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LV<br /><strong>Address:</strong> University of Kota, Kota</p><hr />
<h4>2013-12-09 to 2013-12-24</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LIV<br /><strong>Address:</strong> Indian Institute of Science Education and Research, Pune</p><hr />
<h4>2013-12-02 to 2013-12-15</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> Assam University, Silchar</p><hr />
<h4>2013-12-02 to 2013-12-14</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Quantum mechanics<br /><strong>Address:</strong> J. S. S. Educational Institutions, Suttur</p><hr />
<h4>2013-11-28 to 2013-12-12</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Quantum mechanics<br /><strong>Address:</strong> Indian Institute of Technology, Roorkee</p><hr />
<h4>2013-11-11 to 2013-11-26</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Evolutionary ecology of plants and animals<br /><strong>Address:</strong> P. S. G. R. Krishnammal College for Women, Coimbatore</p><hr />
<h4>2013-11-07 to 2013-11-23</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LIII<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2013-11-06 to 2013-11-19</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Statistical mechanics<br /><strong>Address:</strong> Homi Bhabha Centre for Science Education (TIFR), Mumbai</p><hr />
<h4>2013-10-08 to 2013-10-24</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LII<br /><strong>Address:</strong> Sri Mata Vaishno Devi University, Katra</p><hr />
<h4>2013-09-22 to 2013-10-05</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Updates on biology of infectious diseases<br /><strong>Address:</strong> Haffkine Institute for Training, Research and Testing, Mumbai</p><hr />
<h4>2013-09-16 to 2013-09-30</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics LI<br /><strong>Address:</strong> Barkatullah University, Bhopal</p><hr />
<h4>2013-08-06 to 2013-08-22</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics L<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2013-06-06 to 2013-06-21</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLIX<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2013-05-22 to 2013-05-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Foundations of physics<br /><strong>Address:</strong> Bengal Engineering and Science University, Shibpur</p><hr />
<h4>2013-05-15 to 2013-05-29</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Modern biotechnology: concepts and practice<br /><strong>Address:</strong> Madurai Kamaraj University, Madurai</p><hr />
<h4>2013-05-14 to 2013-05-29</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLVIII<br /><strong>Address:</strong> Vidya Pratishthan's Arts, Science and Commerce College, Baramati</p><hr />
<h4>2013-05-08 to 2013-05-21</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Statistical physics<br /><strong>Address:</strong> Nehru Arts and Science College, Kanhangad</p><hr />
<h4>2013-05-01 to 2013-05-14</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Quantum mechanics<br /><strong>Address:</strong> St Berchman's College, Changanacherry</p><hr />
<h4>2013-04-15 to 2013-04-29</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Traditional and modern approaches in animal taxonomy<br /><strong>Address:</strong> University of Agricultural Sciences, Bengaluru</p><hr />
<h4>2013-04-02 to 2013-04-18</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLVII<br /><strong>Address:</strong> Sri Satya Sai Institute of Higher Learning, Anantapur</p><hr />
<h4>2013-03-05 to 2013-03-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLVI<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2013-02-25 to 2013-03-09</h4><p><strong>Subject:</strong> Engineering<br /><strong>Title:</strong> Vision and challenges of pervasive computing and cloud computing<br /><strong>Address:</strong> G. R. Damodaran College of Science, Coimbatore</p><hr />
<h4>2013-02-04 to 2013-02-16</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Modern genetics: concepts and practice<br /><strong>Address:</strong> Manipal University, Manipal</p><hr />
<h4>2013-02-03 to 2013-02-16</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Advances in plant and animal biotechnology<br /><strong>Address:</strong> Karmaveer Bhaurao Patil College, and other venues, Mumbai</p><hr />
<h4>2013-02-01 to 2013-02-16</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLV<br /><strong>Address:</strong> Christ Church College, Kanpur</p><hr />
<h4>2012-12-24 to 2012-12-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Foundations of physics<br /><strong>Address:</strong> Bengal Engineering and Science University, Shibpur</p><hr />
<h4>2012-12-19 to 2012-12-31</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Experimental biology<br /><strong>Address:</strong> Indian Institute of Science Education and Research, Kolkata</p><hr />
<h4>2012-12-04 to 2012-12-19</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLIV<br /><strong>Address:</strong> V. I. T. University, Chennai Campus</p><hr />
<h4>2012-12-03 to 2012-12-16</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Experimental chemistry<br /><strong>Address:</strong> University of Pune, Pune</p><hr />
<h4>2012-11-19 to 2012-12-03</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Plant sciences<br /><strong>Address:</strong> P. S. G. R. Krishnammal College for Women, Coimbatore</p><hr />
<h4>2012-11-15 to 2012-11-30</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLIII<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2012-11-15 to 2012-11-29</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Traditional and modern approaches in plant taxonomy<br /><strong>Address:</strong> University of Agricultural Sciences, Bengaluru</p><hr />
<h4>2012-10-08 to 2012-10-23</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLII<br /><strong>Address:</strong> Tuljaram Chaturchand College, Baramati</p><hr />
<h4>2012-09-05 to 2012-09-19</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Action zoology: the emerging trends<br /><strong>Address:</strong> University of Allahabad, Allahabad</p><hr />
<h4>2012-09-04 to 2012-09-19</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XLI<br /><strong>Address:</strong> St Xavier's College, Kolkata</p><hr />
<h4>2012-08-27 to 2012-09-08</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Theoretical and computational fluid dynamics<br /><strong>Address:</strong> P. S. G. R. Krishnammal College for Women, Coimbatore</p><hr />
<h4>2012-08-16 to 2012-08-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XL<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2012-07-16 to 2012-07-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXIX<br /><strong>Address:</strong> National Institute of Technology Karnataka, Surathkal</p><hr />
<h4>2012-07-16 to 2012-07-28</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> University of Mumbai, Mumbai</p><hr />
<h4>2012-06-05 to 2012-06-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXVIII<br /><strong>Address:</strong> B. S. Abdur Rahman University, Chennai</p><hr />
<h4>2012-05-15 to 2012-05-30</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXVII<br /><strong>Address:</strong> Institute of Technical Education and Research, Bhubaneswar</p><hr />
<h4>2012-05-14 to 2012-06-02</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Motivational bridge course in mathematical methods in physics and laboratory practices for I and II B.Sc. students<br /><strong>Address:</strong> Yeshwant Mahavidyalaya, Nanded</p><hr />
<h4>2012-04-29 to 2012-05-12</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> The fascinating world of Physics<br /><strong>Address:</strong> Nehru Arts and Science College, Kanhangad</p><hr />
<h4>2012-03-06 to 2012-03-21</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXVI<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2012-02-15 to 2012-03-01</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXV<br /><strong>Address:</strong> St Xavier's College, Ahmedabad</p><hr />
<h4>2012-01-23 to 2012-02-04</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Cell and molecular biology techniques<br /><strong>Address:</strong> Manipal University, Manipal</p><hr />
<h4>2012-01-23 to 2012-02-04</h4><p><strong>Subject:</strong> Engineering<br /><strong>Title:</strong> Paradigms and applications of pattern recognition in image processing and computer vision<br /><strong>Address:</strong> Dr G. R. Damodaran College of Science, Coimbatore</p><hr />
<h4>2012-01-02 to 2012-01-07</h4><p><strong>Subject:</strong> Science education<br /><strong>Title:</strong> Physics for secondary school science teachers<br /><strong>Address:</strong> Gogate Jogalekar College, Ratnagiri</p><hr />
<h4>2012-01-02 to 2012-01-05</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Astronomy<br /><strong>Address:</strong> Birbhum Institute of Engineering and Technology, Suri</p><hr />
<h4>2011-12-26 to 2011-12-31</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Foundations of mathematics<br /><strong>Address:</strong> Bengal Engineering and Science University, Shibpur</p><hr />
<h4>2011-12-02 to 2011-12-17</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXIV<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2011-11-23 to 2011-12-07</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Techniques in neurosciences - behaviour to molecules<br /><strong>Address:</strong> Sophia College, Mumbai</p><hr />
<h4>2011-11-08 to 2011-11-23</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXIII<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2011-10-12 to 2011-10-28</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXII<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2011-08-08 to 2011-08-23</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXXI<br /><strong>Address:</strong> Don Bosco Institute of Technology, Bengaluru</p><hr />
<h4>2011-07-11 to 2011-07-27</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXX<br /><strong>Address:</strong> Indian Institute of Technology Madras, Chennai</p><hr />
<h4>2011-06-15 to 2011-07-08</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Motivational bridge course in mathematical methods in physics and laboratory practices for I and II year B.Sc. students<br /><strong>Address:</strong> Deogiri College, Aurangabad</p><hr />
<h4>2011-06-07 to 2011-06-22</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXIX<br /><strong>Address:</strong> SICES Degree College of Arts, Science and Commerce, Ambernath</p><hr />
<h4>2011-05-16 to 2011-05-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXVIII<br /><strong>Address:</strong> K. I. I. T. University, Bhubaneswar</p><hr />
<h4>2011-05-16 to 2011-05-26</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Foundations of physics for senior school students<br /><strong>Address:</strong> Bengal Engineering and Science University, Shibpur</p><hr />
<h4>2011-03-22 to 2011-04-06</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXVII<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2011-03-01 to 2011-03-11</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Advances in biotechnology<br /><strong>Address:</strong> National Institute for Research in Reproductive Health, Mumbai</p><hr />
<h4>2011-02-28 to 2011-03-13</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Condensed matter physics<br /><strong>Address:</strong> St Thomas College, Palai</p><hr />
<h4>2011-01-18 to 2011-02-02</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXVI<br /><strong>Address:</strong> Ramakrishna Mission Vivekananda College, Chennai</p><hr />
<h4>2011-01-10 to 2011-01-22</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Modern biotechnological techniques<br /><strong>Address:</strong> Manipal University, Manipal</p><hr />
<h4>2010-12-27 to 2010-12-31</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Foundations of mathematics<br /><strong>Address:</strong> Bengal Engineering and Science University, Shibpur, Howrah</p><hr />
<h4>2010-12-15 to 2010-12-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXV<br /><strong>Address:</strong> Indian Academy of Sciences facility, Bengaluru</p><hr />
<h4>2010-12-08 to 2010-12-21</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Recent advances in chemical science and its technological applications<br /><strong>Address:</strong> Sikkim Manipal Institute of Technology, Gangtok</p><hr />
<h4>2010-11-18 to 2010-12-03</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXIV<br /><strong>Address:</strong> Mahatma Gandhi University, Kottayam</p><hr />
<h4>2010-10-20 to 2010-11-02</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Contemporary nonequilibrium thermodynamics and statistical mechanics<br /><strong>Address:</strong> RTM Nagpur University, Nagpur</p><hr />
<h4>2010-10-05 to 2010-10-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXIII<br /><strong>Address:</strong> Shivaji University, Kolhapur</p><hr />
<h4>2010-07-15 to 2010-07-30</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXII<br /><strong>Address:</strong> Bengaluru University, Bengaluru</p><hr />
<h4>2010-06-28 to 2010-07-12</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XXI<br /><strong>Address:</strong> Sree Siddaganga College for Women, Tumkur</p><hr />
<h4>2010-06-14 to 2010-06-25</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Frontiers in atmospheric sciences<br /><strong>Address:</strong> Indian Institute of Tropical Meteorology, Pune</p><hr />
<h4>2010-06-01 to 2010-06-25</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> MBC bridge course in mathematical methods in physics<br /><strong>Address:</strong> Dayanand Science College, Latur</p><hr />
<h4>2010-05-24 to 2010-06-09</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XX<br /><strong>Address:</strong> Manipal University, Manipal</p><hr />
<h4>2010-05-17 to 2010-05-27</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Foundations of physics<br /><strong>Address:</strong> Bengal Engineering and Science University, Shibpur</p><hr />
<h4>2010-01-11 to 2010-01-23</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Biotechnology and modern molecular biology techniques<br /><strong>Address:</strong> Manipal Life Sciences Centre / Manipal University, Manipal</p><hr />
<h4>2010-01-04 to 2010-01-20</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XIX<br /><strong>Address:</strong> Karnatak University, Dharwad</p><hr />
<h4>2009-12-07 to 2009-12-19</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> Bishop Moore College, Mavelikara</p><hr />
<h4>2009-11-23 to 2009-12-08</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XVIII<br /><strong>Address:</strong> University of Calicut, Calicut</p><hr />
<h4>2009-10-26 to 2009-11-09</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XVII<br /><strong>Address:</strong> Carmel College for Women, Nuvem, Goa</p><hr />
<h4>2009-06-26 to 2009-07-11</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XVI<br /><strong>Address:</strong> Osmania University, Hyderabad</p><hr />
<h4>2009-06-15 to 2009-06-29</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Experimental chemistry<br /><strong>Address:</strong> University of Hyderabad, Hyderabad</p><hr />
<h4>2009-06-01 to 2009-06-16</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XV<br /><strong>Address:</strong> Mangalore University, Mangalore</p><hr />
<h4>2009-05-11 to 2009-05-23</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Animal and plant tissue culture<br /><strong>Address:</strong> Rajiv Gandhi Institute of IT and Biotechnology, Pune</p><hr />
<h4>2009-05-07 to 2009-05-22</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XIV<br /><strong>Address:</strong> Alagappa University, Karaikudi, Karaikudi</p><hr />
<h4>2009-03-23 to 2009-04-11</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Motivational bridge courses in mathematical methods in physics and laboratory practices for I and II B.Sc students<br /><strong>Address:</strong> Gogate-Joglekar College, Ratnagiri</p><hr />
<h4>2009-01-19 to 2009-02-03</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XIII<br /><strong>Address:</strong> Bharathidasan University, Tiruchirappalli</p><hr />
<h4>2008-12-22 to 2009-01-07</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XII<br /><strong>Address:</strong> Madurai Kamaraj University</p><hr />
<h4>2008-12-01 to 2008-12-05</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental nonlinear dynamics<br /><strong>Address:</strong> Saha Institute of Nuclear Physics</p><hr />
<h4>2008-07-07 to 2008-07-23</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics XI<br /><strong>Address:</strong> University of Pondicherry</p><hr />
<h4>2008-05-26 to 2008-05-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> The fascinating world of Physics<br /><strong>Address:</strong> Central Mechanical Engineering Research Institure, Durgapr</p><hr />
<h4>2008-05-24 to 2008-06-04</h4><p><strong>Subject:</strong> Engineering<br /><strong>Title:</strong> Student oriented skills for quality teaching and research: science through environment and computers<br /><strong>Address:</strong> HNB Garhwal University, Srinagar, Garhwal, Uttarakhand</p><hr />
<h4>2008-05-16 to 2008-05-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics X<br /><strong>Address:</strong> Bharathiar University, Coimbatore</p><hr />
<h4>2008-01-30 to 2008-02-13</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Vistas in zoological teaching<br /><strong>Address:</strong> University of Allahabad</p><hr />
<h4>2007-10-22 to 2007-11-03</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics IX<br /><strong>Address:</strong> University of Kerala, Thiruvananthapuram</p><hr />
<h4>2007-10-22 to 2007-11-02</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Marine Geology and Geophysics<br /><strong>Address:</strong> National Institute of Oceanography, Goa</p><hr />
<h4>2007-06-09 to 2007-06-14</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Mathematics and its applications<br /><strong>Address:</strong> Central Mechanical Engineering Research Institute, Durgapur</p><hr />
<h4>2007-05-28 to 2007-06-10</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics VIII<br /><strong>Address:</strong> Anna University, Chennai</p><hr />
<h4>2007-05-25 to 2007-06-08</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Advances in biophysics<br /><strong>Address:</strong> Centre for Cellular and Molecular Biology, Hyderabad</p><hr />
<h4>2007-05-14 to 2007-05-26</h4><p><strong>Subject:</strong> Mathematics and Physics<br /><strong>Title:</strong> Topics in Mathematics and Physics<br /><strong>Address:</strong> Ramakrishna Mission, Vivekananda University, Belur Math</p><hr />
<h4>2006-12-11 to 2006-12-23</h4><p><strong>Subject:</strong> Engineering<br /><strong>Title:</strong> Tensors and their applications in engineering sciences<br /><strong>Address:</strong> Indian Institute of Science, Bengaluru</p><hr />
<h4>2006-11-27 to 2006-12-10</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Experimental chemistry<br /><strong>Address:</strong> University of Hyderabad, Hyderabad</p><hr />
<h4>2006-11-07 to 2006-11-20</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Advanced topics in chemistry<br /><strong>Address:</strong> Lady Doak College, Madurai</p><hr />
<h4>2006-07-10 to 2006-07-23</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Phylogenetic biology<br /><strong>Address:</strong> University of Mysore, Mysore</p><hr />
<h4>2005-12-05 to 2005-12-17</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Applied stochastic processes<br /><strong>Address:</strong> Indian Statistical Institute, New Delhi</p><hr />
<h4>2005-11-14 to 2005-11-25</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Physics of the atmosphere<br /><strong>Address:</strong> Centre for Atmospheric and Oceanic Sciences, Indian Institute of Science, Bengaluru</p><hr />
<h4>2005-11-07 to 2005-11-27</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Foundation course in physics and chemistry of the earth<br /><strong>Address:</strong> National Centre of Experimental Mineralogy and Petrology, University of Allahabad</p><hr />
<h4>2005-09-26 to 2005-10-07</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Probability, stochastic processes and applications<br /><strong>Address:</strong> Cochin University of Science and Technology, Kochi</p><hr />
<h4>2005-09-19 to 2005-09-30</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> S. B. College, Changanassery, Kerala</p><hr />
<h4>2005-06-25 to 2005-07-06</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Earth system science<br /><strong>Address:</strong> Indian Academy of Sciences, Bengaluru</p><hr />
<h4>2005-05-25 to 2005-06-08</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Interdisciplinary approaches in biology<br /><strong>Address:</strong> Centre for Cellular and Molecular Biology, Hyderabad</p><hr />
<h4>2005-05-16 to 2005-05-21</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Foundations of mechanics for senior school students<br /><strong>Address:</strong> Central Mechanical Engineering Institute, Durgapur</p><hr />
<h4>2005-05-09 to 2005-05-22</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics VII<br /><strong>Address:</strong> Indian Institute of Technology, Guwahati</p><hr />
<h4>2005-05-02 to 2005-05-14</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Instructional workshop on cryptology<br /><strong>Address:</strong> Cochin University of Science and Technology, Kochi</p><hr />
<h4>2005-02-13 to 2005-02-25</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Photonics and materials<br /><strong>Address:</strong> University of Madras, Chennai</p><hr />
<h4>2004-12-14 to 2004-12-20</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Developmental biology<br /><strong>Address:</strong> Indian Institute of Science, Bengaluru</p><hr />
<h4>2004-12-08 to 2004-12-21</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Animal behaviour<br /><strong>Address:</strong> Madurai Kamaraj University, Madurai</p><hr />
<h4>2004-12-07 to 2004-12-21</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Plant genetic engineering<br /><strong>Address:</strong> Madurai Kamaraj University, Madurai</p><hr />
<h4>2004-11-01 to 2004-11-15</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics VI<br /><strong>Address:</strong> University of Mysore, Mysore</p><hr />
<h4>2004-10-25 to 2004-11-07</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics V<br /><strong>Address:</strong> Bhavnagar University, Bhavnagar</p><hr />
<h4>2004-01-19 to 2004-01-31</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Lasers and applications in chemical processes<br /><strong>Address:</strong> University of Madras, Chennai</p><hr />
<h4>2003-12-18 to 2003-12-31</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Frontiers in inorganic chemistry<br /><strong>Address:</strong> Indian Institute of Technology, Kanpur</p><hr />
<h4>2003-12-01 to 2003-12-13</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Analysis and applications<br /><strong>Address:</strong> Berhampur University, Berhampur</p><hr />
<h4>2003-12-01 to 2003-12-12</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Physics of the atmosphere and the ocean<br /><strong>Address:</strong> Centre for Atmospheric and Oceanic Sciences, Indian Institute of Science, Bengaluru</p><hr />
<h4>2003-11-03 to 2003-11-16</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics IV<br /><strong>Address:</strong> Saurashtra University, Rajkot</p><hr />
<h4>2003-11-03 to 2003-11-15</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Earth sciences<br /><strong>Address:</strong> Jawaharlal Nehru Technological University, Hyderabad</p><hr />
<h4>2003-10-28 to 2003-11-10</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics III<br /><strong>Address:</strong> Goa University, Goa</p><hr />
<h4>2003-07-02 to 2003-07-14</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Molecular and developmental genetics<br /><strong>Address:</strong> Banaras Hindu University, Varanasi</p><hr />
<h4>2003-02-16 to 2003-03-02</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Quantum chemistry<br /><strong>Address:</strong> University of Hyderabad, Hyderabad</p><hr />
<h4>2003-01-27 to 2003-02-10</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Molecular genetics<br /><strong>Address:</strong> Madurai Kamaraj University, Madurai</p><hr />
<h4>2002-12-09 to 2002-12-23</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Reproductive biology<br /><strong>Address:</strong> Department of Zoology, Karnatak Univerity, Dharwad</p><hr />
<h4>2002-12-02 to 2002-12-21</h4><p><strong>Subject:</strong> Earth sciences<br /><strong>Title:</strong> Physics of earthquakes<br /><strong>Address:</strong> Tezpur University, Tezpur</p><hr />
<h4>2002-12-02 to 2002-12-14</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Coding theory, cryptography and discrete mathematics<br /><strong>Address:</strong> Department of Mathematics, Panjab University, Chandigarh</p><hr />
<h4>2002-11-25 to 2002-12-07</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Immunology<br /><strong>Address:</strong> Interdisciplinary School of Health Sciences, University of Pune, Pune</p><hr />
<h4>2002-11-21 to 2002-12-07</h4><p><strong>Subject:</strong> Chemistry<br /><strong>Title:</strong> Spectroscopy, chemical reactions and biology<br /><strong>Address:</strong> Viswa Bharati, Santiniketan and S. N. Bose Centre, Kolkata</p><hr />
<h4>2002-10-18 to 2002-10-31</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics II<br /><strong>Address:</strong> Indira Gandhi Centre for Atomic Research, Department of Atomic Energy, Kalpakkam</p><hr />
<h4>2002-10-01 to 2002-10-15</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> St Stephen's College, University of Delhi, Delhi</p><hr />
<h4>2002-01-27 to 2002-02-10</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Molecular genetics<br /><strong>Address:</strong> School of Biological Sciences, Centre for Excellence in Genomic Sciences, Madurai Kamaraj University, Madurai</p><hr />
<h4>2001-12-10 to 2001-12-21</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Analysis, probability and statistics<br /><strong>Address:</strong> C. M. S. College, Kottayam, Kerala</p><hr />
<h4>2001-12-03 to 2001-12-15</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Linear algebra<br /><strong>Address:</strong> Harish Chandra Research Institute, Allahabad</p><hr />
<h4>2001-11-18 to 2001-11-30</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> University of Hyderabad, Hyderabad</p><hr />
<h4>2001-10-12 to 2001-10-29</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Experimental physics I<br /><strong>Address:</strong> Department of Physics, Goa University, Goa</p><hr />
<h4>2001-09-10 to 2001-09-22</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Genetics and evolution<br /><strong>Address:</strong> Department of Studies in Zoology, University of Mysore, Mysore</p><hr />
<h4>2000-11-06 to 2000-11-18</h4><p><strong>Subject:</strong> Physics<br /><strong>Title:</strong> Theoretical physics<br /><strong>Address:</strong> Bishop Moore College, Mavelikara</p><hr />
<h4>2000-11-06 to 2000-11-17</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Modern biology<br /><strong>Address:</strong> Indian Institute of Chemical Biology, Kolkata</p><hr />
<h4>2000-06-01 to 2000-06-01</h4><p><strong>Subject:</strong> Life sciences<br /><strong>Title:</strong> Animal sciences<br /><strong>Address:</strong> Department of Zoology, Karnatak University, Dharwad</p><hr />
<h4>1999-12-06 to 1999-12-18</h4><p><strong>Subject:</strong> Mathematics<br /><strong>Title:</strong> Linear algebra<br /><strong>Address:</strong> Centre for Advanced Study in Mathematics, Panjab University, Chandigarh</p><hr />
