<h1>Special Publications</h1>
<h2>Publications may be ordered from the Academy.</h2>

<h4>Note: </h4>
<ol>
	<li>Price includes postages and packing charges.</li>
	<li>Copies will be supplied till stocks last.</li>
	<li>Payment should be prepared in favour of 'Indian Academy of Sciences, Bengaluru'.</li>
</ol>
<ul class="list-unstyled gap-above">
	<li class="journal-article-list"><p><span>pp 318</span><span></span><span>INR 200</span></p><p>Memoirs on Crystal Physics</p><p>C. V. Raman</p></li>
	<li class="journal-article-list"><p><span>pp 160</span><span>1959</span><span>INR 150</span></p><p>Lectures on Physical Optics Part - I</p><p>C. V. Raman</p></li>
	<li class="journal-article-list"><p><span>pp 164</span><span>1968<span class="text-primary">*</span></span><span>INR 100</span></p><p>Physiology of Vision</p><p>C. V. Raman</p></li>
	<li class="journal-article-list"><p><span>pp 78</span><span>1975</span><span>INR 100</span></p><p>Special Publication-1 Lectures on Catalysis</p></li>
	<li class="journal-article-list"><p><span>pp 60</span><span>1975</span><span>INR 100</span></p><p>Special Publication-2 Lectures on Physics</p></li>
	<li class="journal-article-list"><p><span>pp 234</span><span>1978</span><span>INR 150</span></p><p>The Aryabhata Project</p><p>U. R. Rao, K. Kasturirangan</p></li>
	<li class="journal-article-list"><p><span>pp 330</span><span>1980</span><span>INR 250</span></p><p>Rural Technology</p><p>Amulya Kumar N. Reddy</p></li>
	<li class="journal-article-list"><p><span>pp 162</span><span>1981</span><span>INR 100</span></p><p>Alloys Design</p><p>S. Ranganathan, V. S. Arunachalam, R. W. Cahn</p></li>
	<li class="journal-article-list"><p><span>pp 124</span><span>1982</span><span>INR 100</span></p><p>Nuclear Tracks-Space Physics Geophysics and Nuclear Physics</p><p>J. N. Goswami</p></li>
	<li class="journal-article-list"><p><span>pp 313</span><span>1982</span><span>INR 150</span></p><p>Crystallographic Statistics-Progress and Problems</p><p>S. Ramaseshan, M. F. Richardson, A. J. C. Wilson</p></li>
	<li class="journal-article-list"><p><span>pp 1110</span><span>1982, 1983, 1993</span><span>INR 600</span></p><p>Surveys in Fluid Mechanics (Volume 1-3)</p><p>R. Narasimha, S. M. Deshpande, APJ Abdul Kalam</p></li>
	<li class="journal-article-list"><p><span>pp 255</span><span>1983</span><span>INR 150</span></p><p>Wood Heat for Cooking</p><p>K. Krishna Prasad, P. Verhaart</p></li>
	<li class="journal-article-list"><p><span>pp 252</span><span>1983</span><span>INR 150</span></p><p>Contributions to Crystallography</p><p>C. N. R. Rao</p></li>
	<li class="journal-article-list"><p><span>pp 152</span><span>1984</span><span>INR 150</span></p><p>Gravitation and Relativistic Astrophysics</p><p>A. R. Prasanna, J. V. Narlikar, C. V. Vishveshwara</p></li>
	<li class="journal-article-list"><p><span>pp 180</span><span>1985</span><span>INR 100</span></p><p>Extragalactic Energetic Sources</p><p>V. K. Kapahi</p></li>
	<li class="journal-article-list"><p><span>pp 428</span><span>1985</span><span>INR 200</span></p><p>Photons, Galaxies and Stars</p><p>R. Hanbury Brown</p></li>
	<li class="journal-article-list"><p><span>pp 355</span><span>1985</span><span>INR 200</span></p><p>Water Resources Systems Planning</p><p>M. C. Chaturvedi, Peter Rogers</p></li>
	<li class="journal-article-list"><p><span>pp 172</span><span>1985</span><span>INR 100</span></p><p>Supermovae, their Progenitors and Remnants</p><p>G. Srinivasan, V. Radhakrishnan</p></li>
	<li class="journal-article-list"><p><span>pp 332</span><span>1987</span><span>INR 200</span></p><p>Reactions and Reaction Engineering</p><p>R. A. Mashelkar, R. Kumar</p></li>
	<li class="journal-article-list"><p><span>pp 280</span><span>1987</span><span>INR 150</span></p><p>Reliability and Fault - Tolerance issues in Real-Time Systems</p><p>N. Viswanadham</p></li>
	<li class="journal-article-list"><p><span>pp 177</span><span>1988</span><span>INR 300</span></p><p>C. V. Raman Pictorial Biography</p><p>C. Ramachandra, S. Ramaseshan</p></li>
	<li class="journal-article-list"><p><span>pp 168</span><span>1988</span><span>INR 100</span></p><p>Advanced Ceramics</p><p>E. C. Subbarao</p></li>
	<li class="journal-article-list"><p><span>pp 166</span><span>1988</span><span>INR 100</span></p><p>Composite Materials and Structures</p><p>K. A. V. Pandalai</p></li>
	<li class="journal-article-list"><p><span>pp 90</span><span>1990</span><span>INR 100</span></p><p>Bird Flight</p><p>S. Dhawan</p></li>
	<li class="journal-article-list"><p><span>pp 170</span><span>1991</span><span>INR 100</span></p><p>Recent Advances in Modelling and Control of Stochastic Systems</p><p>N. Viswanadham, V. S. Borkar</p></li>
	<li class="journal-article-list"><p><span>pp 746</span><span>1991</span><span>INR 500</span></p><p>Perspectives in Structural Biology</p><p>M. Vijayan, N. Yathindra, A. S. Kolaskar</p></li>
	<li class="journal-article-list"><p><span>pp 224</span><span>1992</span><span>INR 150</span></p><p>Parallel and Real Time Distributed Computing</p><p>R. K. Shyamasundar</p></li>
	<li class="journal-article-list"><p><span>pp 254</span><span>1994</span><span>INR 100</span></p><p>Biogeochemistry of the Arabian Sea</p><p>D. Lal</p></li>
	<li class="journal-article-list"><p><span>pp 422</span><span>1997</span><span>INR 200</span></p><p>The Monsoon trough boundary layer</p><p>R. Narasimha, D. R. Sikka, A. Prabhu</p></li>
	<li class="journal-article-list"><p><span>pp 295</span><span>1998</span><span>INR 250</span></p><p>Rare Nuclear Process in Low Energy Heavy lon Physics</p><p>P. Sugathan, N. Madhavan, R. Singh, A. K. Sinha</p></li>
	<li class="journal-article-list"><p><span>pp 234</span><span>1999</span><span>INR 200</span></p><p>Isotopes in the Solar System</p><p>J. N. Goswami, S. Krishnaswami</p></li>
	<li class="journal-article-list"><p><span>pp 236</span><span>2000</span><span>INR 325</span></p><p>Percolation Theory and Particle System</p><p>Rahul Roy</p></li>
	<li class="journal-article-list"><p><span>pp 254</span><span>2000, 2006</span><span>INR 470</span></p><p>Butter Flies of Peninsular India</p><p>Madhav Gadgil</p></li>
	<li class="journal-article-list"><p><span>pp 142</span><span>2001</span><span>INR 185</span></p><p>Mathematical Analysis</p><p>Alladi Sitaram, Vishwambhar Pati</p></li>
	<li class="journal-article-list"><p><span>pp 201</span><span>2001</span><span>INR 190</span></p><p>Probability and Statistics</p><p>Mohan Delampady, T. Krishnan, S. Ramasubramanian</p></li>
	<li class="journal-article-list"><p><span>pp 288</span><span>2002</span><span>INR 290</span></p><p>Fresh Water Fishes of Peninsular India</p><p>R. J. Rajit Daniel</p></li>
	<li class="journal-article-list"><p><span>pp 102</span><span>2003</span><span>INR 125</span></p><p>Number Theory</p><p>Shailesh Shirali, C. S. Yogananda</p></li>
	<li class="journal-article-list"><p><span>pp 870</span><span>2004</span><span>INR 500</span></p><p>Frontiers in Materials Science</p><p>Baldev Raj and K. BhanuShankara Rao</p></li>
	<li class="journal-article-list"><p><span>pp 268</span><span>2005</span><span>INR 315</span></p><p>Amphibians of Peninsular India</p><p>R. J. Rajit Daniel</p></li>
	<li class="journal-article-list"><p><span>pp 157</span><span>2007</span><span>INR 100</span></p><p>Ray Chaudhuri Equation At the Cross Roads</p><p>Naresh Dadhich, Pankaj Joshi, Probir Roy</p></li>
	<li class="journal-article-list"><p><span>pp 368</span><span>2010</span><span>INR 300</span></p><p>Lilavati's Daughters - The Women Scientists of India</p><p>Rohini M. Godbole, Ram Ramaswamy</p></li>
</ul>
<ul class="list-unstyled gap-above">
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 291</span><span>1982</span><span>INR 150</span><span>USD 30</span></p><p>Topics in Nonlinear Optics - Collected Works</p><p>N. Blombergen</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 428</span><span>1985</span><span>INR 200</span><span>USD 30</span></p><p>Photons, Galaxies and Stars: Selected papers of R. Hanbury Brown</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 632</span><span>1985</span><span>INR 250</span><span>USD 35</span></p><p>Laser Spectroscopy and other Topics: Selected Papers of G. W. Series</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 585</span><span>1988</span><span>INR 500</span><span>USD 50</span></p><p>Scientific Papers of Sir C. V. Raman - Vol. 1 Scattering of Light</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 643</span><span>1988</span><span>INR 500</span><span>USD 50</span></p><p>Scientific Papers of Sir C. V. Raman - Vol. 2 Acoustics</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 553</span><span>1988</span><span>INR 500</span><span>USD 50</span></p><p>Scientific Papers of Sir C. V. Raman - Vol. 3 Optics</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 743</span><span>1988</span><span>INR 500</span><span>USD 50</span></p><p>Scientific Papers of Sir C. V. Raman - Vol. 4 Optics of Minerals and Diamonds</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 849</span><span>1988</span><span>INR 500</span><span>USD 50</span></p><p>Scientific Papers of Sir C. V. Raman - Vol. 5 Physics of Crystals</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 615</span><span>1988</span><span>INR 500</span><span>USD 50</span></p><p>Scientific Papers of Sir C. V. Raman - Vol. 6 Floral Colours and Visual Perception</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 570</span><span>1988</span><span>INR 295</span><span>USD 35</span></p><p>Journey into Light - The Life and Science of C. V. Raman</p><p>Editor: G. Venkataraman</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 177</span><span>1988</span><span>INR 200</span><span>USD 25</span></p><p>C. V. Raman - A Pictorial Biography</p><p>Editors: S. Ramaseshan, C. Ramachandra Rao</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 454</span><span>1988</span><span>INR 100</span><span>USD 20</span></p><p>Developments in Fluid Mechanics and Space Technology -Dedicated to Satish Dhawan</p><p>Editors: R. Narasimha, A. P. J. Abdul Kalam, </p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 307</span><span>1989</span><span>INR 180</span><span>USD 30</span></p><p>Essays on Particles and Fields - M. G. K. Menon Festschrift</p><p>Editors: R. R. Daniel, B. V. Sreekantan</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 322</span><span>1990</span><span>INR 180</span><span>USD 30</span></p><p>From Mantles to Meteorites - A Garland of Perspectives - Devendra Lal Festschrift</p><p>Editors:<a href="">K. Gopalan</a>, <a href="">Vinod K. Gaur</a>, <a href="">B. L. K. Somayajulu</a>, <a href="">J. D. Macdougall</a>, </p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 722</span><span>1991</span><span>INR 500</span><span>USD 65</span></p><p>Molecular Conformations and Biological Interactions - G. N. Ramachandran Festschrift</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 406</span><span>1991</span><span>INR 250</span><span>USD 30</span></p><p>Researches on Cellular Slime Moulds - Selected Papers of J. T. Bonner</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 460</span><span>1992</span><span>INR 250</span><span>USD 30</span></p><p>Hepatitis B Virus and the Public Health - Selected Papers of B. S. Blumberg.</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 702</span><span>1995</span><span>INR 600</span><span>USD 60</span></p><p>Directory of Fellows (two volumes)</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 635</span><span>1996</span><span>INR 1500</span><span>USD 40</span></p><p>Collected Works of Dorothy Hodgkin - Vol. 1 Insulin</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 762</span><span>1996</span><span>INR 1500</span><span>USD 40</span></p><p>Collected Works of Dorothy Hodgkin - Vol. 2 Cholesterol, Penicillin and other Antibiotics and Vitamin B12</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 833</span><span>1996</span><span>INR 1500</span><span>USD 40</span></p><p>Collected Works of Dorothy Hodgkin - Vol. 3 General Crystallorgaphy and Essays</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 240</span><span>1999</span><span>INR 350</span><span>USD 120</span></p><p>From White Dwarfs to Black Holes: The Legacy of S. Chandrasekhar</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 978</span><span>1983</span><span>INR 1000</span></p><p>Prof. K. R. Ramanathan's Selected Papers - 2 volumes</p><p>Indian Academy of Sciences</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 320</span><span>1985</span><span>INR 350</span></p><p>Topics in Genetic Analysis- Selected Papers</p><p>G. Pontecorvo</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 632</span><span>1985</span><span>INR 550</span></p><p>Laser Spectroscopy and other topics - Selected Papers</p><p>G. W. Series</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 421</span><span>1985</span><span>INR 450</span></p><p>Raja Ramanna 60<sup>th</sup> Birthday Felicitation Volume</p><p>IASc, INSA, IPA</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 263</span><span>1986</span><span>INR 250</span></p><p>Computer Modelling and Applications in Metallurgical Research and Industry</p><p>D. N. Sah, R. Vijayaraghavan, P. R. Roay</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 4126</span><span>1988</span><span>INR 2500</span></p><p>Scientific Papers of C. V. Raman - 6 Volumes</p><p>S. Ramaseshan</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 324</span><span>1989</span><span>INR 350</span></p><p>Essays on Particles and Fields (Prof. M. G. K. Menon Festschrift)</p><p>R. R. Daniel, B. V. Sreekantan</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 322</span><span>1990</span><span>INR 350</span></p><p>From Mantle to Meteorities-A Garland of Perspectives (Prof. D. Lal Festschrift)</p><p>K. Gopalan, Vinod K., B. L. K. Somayajulu, J. D. Macdougali</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 722</span><span>1991</span><span>INR 500</span></p><p>Molecular Conformation and Biological Interactions (Prof. G. N. Ramachandran Festschrift)</p><p>P. Balaram, S. Ramaseshan</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 406</span><span>1991</span><span>INR 350</span></p><p>Researches on Cellular Slime Moulds (Selected Papers)</p><p>J. T. Bonner</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 460</span><span>1992</span><span>INR 450</span></p><p>Hepatitis B Virus and the Public Health (Selected Papers)</p><p>B. S. Blumberg</p></li>
	<li class="journal-article-list"><p><span>General Collected Works, Festschrifts etc.</span><span>pp 1632</span><span>1994</span><span>INR 3500</span></p><p>The collected works of Dorothy Crowfoot Hodgkin Volume - I, II &amp; III</p><p>G. G. Dodson, J. P. Glusker, S. Ramaseshan, K. Venkatesan</p></li>
</ul>
<ul class="list-unstyled">
	<li class="journal-article-list"><p><span>Engineering/Computer Science</span><span>pp 321</span><span>1982</span><span>INR 150</span><span>USD 30</span></p><p>Materials Processing in Space - A Workshop</p><p>Editors: S. Ramaseshan, M. K. Tiwari</p></li>
	<li class="journal-article-list"><p><span>Engineering/Computer Science</span><span>pp 356</span><span>1985</span><span>INR 200</span><span>USD 30</span></p><p>Water Resources Systems Planning</p><p>Editors: M. C. Chaturvedi, Peter Rogers</p></li>
	<li class="journal-article-list"><p><span>Engineering/Computer Science</span><span>pp 332</span><span>1987</span><span>INR 200</span><span>USD 30</span></p><p>Reactions and Reaction Engineering</p><p>Editors: R. A. Mashelkar, R. Kumar</p></li>
	<li class="journal-article-list"><p><span>Engineering/Computer Science</span><span>pp 283</span><span>1987</span><span>INR 150</span><span>USD 20</span></p><p>Reliability and Fault-Tolerance Issues in Real-Time Systems</p><p>Editor: N. Viswanadham</p></li>
	<li class="journal-article-list"><p><span>Engineering/Computer Science</span><span>pp 170</span><span>1991</span><span>INR 100</span><span>USD 20</span></p><p>Recent Advances in Modelling and Control of Stochastic Systems</p><p>Editors: N. Viswanadham, V. S. Borkar</p></li>
	<li class="journal-article-list"><p><span>Engineering/Computer Science</span><span>pp 224</span><span>1992</span><span>INR 150</span><span>USD 25</span></p><p>Parallel and Real Tiwarime Distributed Computating</p><p>Editor: R. K. Shyamasundar</p></li>
</ul>
<ul class="list-unstyled">
	<li class="journal-article-list"><p><span>Astrophysics and Astronomy</span><span>pp 180</span><span>1983</span><span>INR 100</span><span>USD 20</span></p><p>Extragalactic Energetic Sources</p></li>
	<li class="journal-article-list"><p><span>Astrophysics and Astronomy</span><span>pp 178</span><span>1985</span><span>INR 100</span><span>USD 20</span></p><p>Supernovae, their Progenitors and Remnants</p></li>
</ul>
<ul class="list-unstyled">
	<li class="journal-article-list"><p><span>Earth and Planetary Science</span><span>pp 420</span><span>1997</span><span>INR 350</span><span>USD 40</span></p><p>Monsoon Trough Boundary Layer Experiment (MONTBLEX)</p></li>
	<li class="journal-article-list"><p><span>Earth and Planetary Science</span><span>pp 234</span><span>1998</span><span>INR 250</span><span>USD 35</span></p><p>Isotopes in the Solar System - Proceedings of the International Conference, Physical Research Laboratory, Ahmedabad (HB)</p><p>Editors: J. N. Goswami, S. Krishnaswami</p></li>
</ul>
<ul class="list-unstyled">
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 568</span><span>1973</span><span>INR 450</span></p><p>Liquid Crystals (Proceedings of the 1973 International Conference)</p><p>S. Chandrasekhar</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 529</span><span>1980</span><span>INR 450</span></p><p>Computing in Crystallography</p><p>R. Diamond, S. Ramaseshan, K. Venkatesan</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 321</span><span>1982</span><span>INR 350</span></p><p>Materials Processing in Space - A Workshop</p><p>S. Ramaseshan, M. K. Tiwari</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 284</span><span>1982</span><span>INR 350</span></p><p>International Colloquium on Baryon Non Conservation (ICOBAN)</p><p>V. S. Narasimhan, P. Roy, K. V. L. Sarma, B. V. Sreekantan</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 836</span><span>1984</span><span>INR 450</span></p><p>Proceedings of the International Symposium on Biomolecular Structure &amp; Interactions</p><p>IASc and IISc</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 555</span><span>1989</span><span>INR 450</span></p><p>Direct Nuclear Reactions-Proceedings of the International Seminar-1989</p><p>N. G. Puttaswamy</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 554</span><span>1991</span><span>INR 450</span></p><p>A Variety of Plasmas - Proceedings of the 1989 International Conference on Plasma Physics</p><p>A. Sen, P. K. Kaw</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 546</span><span>1993</span><span>INR 450</span></p><p>Proceedings of the tenth DAE Symposium on High Energy Physics</p><p>Sunanda Banerjee, Probir Roy</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 326</span><span>1995</span><span>INR 350</span></p><p>PULSARS- Proceedings of the Diamond Jubilee Symposium of the IASc</p><p>C. Srinivasan</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 178</span><span>1997</span><span>INR 250</span></p><p>Recent Advances in Plasma Physics</p><p>B. Buti</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 316</span><span>1998</span><span>INR 350</span></p><p>Workshop on High Energy Physics Phenomenology (WHEPP-5)</p><p>Rajiv V. Gavai, Rohini M. Godbole</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 296</span><span>1999</span><span>INR 350</span></p><p>Rare Nuclear Processes in Low Energy Heavy Ion Physics</p><p>P. Sugathan, N. Madhavan, A. K. Sinha, R. Singh</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 292</span><span>2000</span><span>INR 350</span></p><p>The Physics of Black Holes</p><p>N. Mukunda, J. Pasupathy, C. V. Vishveshwara</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 360</span><span>2000</span><span>INR 350</span></p><p>Proceedings of the Sixth Workshop on High Energy Physics Phenomenology (WHEPP-6)</p><p>Rahul Basu</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 234</span><span>2001</span><span>INR 250</span></p><p>Physics with Multi Detector Array</p><p>Binay Dasmahapatra</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 326</span><span>2001</span><span>INR 350</span></p><p>Optical Solitons: Theory and Experiments</p><p>K. Porsezian, V. C. Kuriakose</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 318</span><span>2001</span><span>INR 350</span></p><p>Foundations of Quantum Theory and Quantum Optics (Volume I)</p><p>Shasanka Mohan Roy</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 270</span><span>2002</span><span>INR 350</span></p><p>Foundations of Quantum Theory and Quantum Optics (Volume II)</p><p>Rupmanjari Ghosh</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 494</span><span>2002</span><span>INR 450</span></p><p>Proceedings of the International Symposium on Advances in Superconductivity and Magnetism: Materials Mechanisms and Devices</p><p>R. Pinto, R. Nagarajan, A. K. Grover</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 380</span><span>2002</span><span>INR 350</span></p><p>Proceedings of the Ninth International Conference on Heavy Ion Accelerator Technology</p><p>A. Roy, S. K. Datta, M. B. Kurup, S. Kailas</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 296</span><span>2002</span><span>INR 350</span></p><p>Mesoscopic and Disordered Systems</p><p>A. M. Jayannavar, H. R. Krishnamurthy, A. K. Raychaudhuri</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 486</span><span>2003</span><span>INR 450</span></p><p>Liquid Crystals and other Soft Materials</p><p>B. K. Sadashiva</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 246</span><span>2003</span><span>INR 250</span></p><p>Proceedings of the Seventh Workshop on High Energy Physics Phenomenology (WHEPP-7)</p><p>Biswarup Mukhopadhyaya</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 559</span><span>2003</span><span>INR 450</span></p><p>Proceedings of the Fourth International Conference 2001 on Physics and Astrophysics of QUARK-GLUON PLASMA</p><p>Bikash Sinha, Dinesh Srivastava, Yogendra Pathak Viyogi</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 278</span><span>2004</span><span>INR 250</span></p><p>ICGC - 2004 Proceedings of the Fifth International Conference on Gravitation and Cosmology</p><p>B. R. Iyer, V. C. Kuriakose, C. V. Vishveshwara</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 324</span><span>2004</span><span>INR 350</span></p><p>Proceedings of DAE-BRNS Eighth Workshop on High Energy Physics Phenomenology (WHEPP-8)</p><p>S. Uma Sankar, Urjit A. Yajnik</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 480</span><span>2004</span><span>INR 450</span></p><p>Proceedings of the Conference on Neutron Scattering</p><p>R. Mukhopadhyay, V. K. Aswal, V. C. Rakhecha</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 656</span><span>2004</span><span>INR 450</span></p><p>Proceedings of the IX International Symposium on Particles, Strings and Cosmology</p><p>D. P. Roy, Sunanda Banerjee, K. Sridhar</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 636</span><span>2005</span><span>INR 450</span></p><p>Perspectives in Nonlinear Dynamics (PNLD-2004)</p><p>Ramakrishna Ramaswamy, Rajarshi Roy, Neelima Gupte</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 1192</span><span>2005</span><span>INR 450</span></p><p>Proceedings of the 22nd IUPAP International Conference on Statistical Physics</p><p>Sushanta Dattagupa, H. R. Krishnamurthy, Rahul Pandit, T. V. Ramakrishnan, Diptimam Sen</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 438</span><span>2005</span><span>INR 450</span></p><p>Proceedings of the National Conference on Nanoscience and Technology 2005</p><p>A. K. Sood, K. N. Ganesh, C. S. Sundar, A. K. Raychaudhuri</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 314</span><span>2006</span><span>INR 350</span></p><p>Current Trends in Vortex State Physics</p><p>S. K. Malik, A. K. Grover, S. N. Bhatia</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 440</span><span>2006</span><span>INR 450</span></p><p>Proceedings of the Ninth Workshop on High Energy Physics Phenomenology (WHEPP-9)</p><p>Pankaj Agrawal, Ajit M. Srivastava</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 538</span><span>2007</span><span>INR 450</span></p><p>Proceedings of the Linear Collider Workshop - 2006</p><p>Rohini M. Godbole, Atul Gurtu</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 236</span><span>2007</span><span>INR 250</span></p><p>Proceedings of the workshop on Physics Accelerator Driven Sub-Critical System for Energy &amp; Transmutation - 2006</p><p>V. Kumar, P. K. Nema, S. Kailas, S. B. Degweker, S. Ganesan</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 190</span><span>2008</span><span>INR 250</span></p><p>Proceedings of the International Workshop on The Physics of Mesoscopic &amp; Disordered Materials</p><p>R. Prasad, S. A. Ramakrishna</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 602</span><span>2008</span><span>INR 450</span></p><p>Proceedings of the International Symposium on Neutron Scattering - 2008</p><p>R. Mukhopadhyay, S. L. Chaplot</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 248</span><span>2008</span><span>INR 250</span></p><p>Proceedings of the Conference and Workshop on Perspectives in Nonlinear Dynamics</p><p>Neelima Gupte, Ram Ramaswamy</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 646</span><span>2009</span><span>INR 450</span></p><p>Current Trends in Science - IASc Platinum Jobilee Special</p><p>N. Mukunda</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 151</span><span>2009</span><span>INR 150</span></p><p>Diversity in Materials Science</p><p>S. B. Krupanidhi, H. L. Bhat</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 304</span><span>2009</span><span>INR 350</span></p><p>Proceedings of the Tenth Workshop on High Energy Physics Phenomenology (WHEPP-X)</p><p>Rahul Basu</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 411</span><span>2009</span><span>INR 450</span></p><p>Non-Hermitian Hamiltonians in Quantum Physics</p><p>Sudhir R. Jain, Zafar Ahmed</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 552</span><span>2010</span><span>INR 450</span></p><p>Proceedings of the 9<sup>th</sup> DAE-BRNS National Laser Symposium (Parts I &amp; II)</p><p>L.M. Gantayet, K. Dasgupta, Sunita Singh, B. M. Suri, D. J. Biswas, S. Sinha, S. Kundu</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 298</span><span>2010</span><span>INR 350</span></p><p>International Symposium on Nuclear Physics</p><p>R. K. Choudhury, A. K. Mohanty, A. Saxena, K. Mahata, S. Santra</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 254</span><span>2011</span><span>INR 250</span></p><p>Proceedings of the Conference and Workshop on Perspectives in Nonlinear Dynamics (PNLD-2010)</p><p>Neelima Gupte, Arul Lakshminarayan, Ram Ramaswamy</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 127</span><span>2011</span><span>INR 150</span></p><p>Proceedings of the XI Workshop on High Energy Physics Phenomenology (WHEPP-XI)</p><p>Anjan S. Joshipura, Subhendra Mohanty, Saurabh D. Rindani</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 232</span><span>2011</span><span>INR 250</span></p><p>Chandra 2010: Proceedings of the Chandrasekhar Centenary</p><p>T. Padmanabhan</p></li>
	<li class="journal-article-list"><p><span>Conference Proceedings</span><span>pp 429</span><span>2012</span><span>INR 450</span></p><p>Proceedings on the 25<sup>th</sup> International Symposium on Lepton-Photon Interactions at High Energies (Part I)</p><p>Rohini M. Godbole, Naba K. Mondal</p></li>
</ul>

