<h1>Dragonflies and Damselflies of Peninsular India - A Field Guide</h1>
<h2>&nbsp;</h2>
<p>The online version of this book is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/2.5/" target="_blank">Creative Commons Attribution-NonCommercial-ShareAlike 2.5 License.</a></p>
<p>The Indian subcontinent is one of the biologically richest regions of the world. Two global biodiversity hot spots, namely the eastern Himalayas and the Western Ghats, are in this region. Another biologically rich region, Sri Lanka, is just to the south of the subcontinent. The subcontinent is rich in odonates (damselflies and dragonflies); about 500 species are known. The dragonflies of the region are taxonomically well described thanks to the monumental work of Fraser. However, the natural history and distribution of most of the species is barely known. This lacuna is largely due to the lack of user-friendly field guides for amateur naturalists and students.</p>
<p>As an initiative to generate interest in dragonflies among naturalists and students, Indian Academy of Sciences is publishing a field guide on the odonates of Peninsular India. The book is being published as part of Project Lifescape of the Academy. This project aims at producing user-friendly field guides and other resources to encourage field-based biology research among students.</p>
<p>The book is divided into three parts. The first part gives a detailed account of the natural history of Odonata. The second part gives keys for the identification of odonate families for larval and adult stages. The third section gives species accounts for 26 damselflies and 34 dragonflies of Peninsular India. The book is lavishly illustrated with colour photographs or specimen scans of all the species described. In addition, the book also provides a checklist of odonates for the region (178 species) and a glossary of technical terms. The novelty of the book is provision of common English names of all species. The first edition of this book is entirely downloadable freely from this website.</p>
<p>The book is downloadable in three parts, each a PDF file:</p>
<ul>
	<li class="gap-above-small">Part 1 - <a href="<?=RESOURCES_URL?>Other_Publications/Overview/Dragonflies/odonates_introduction.pdf" target="_blank">Introduction</a><br />(includes natural history and keys)</li>
	<li class="gap-above-small">Part 2 - <a href="<?=RESOURCES_URL?>Other_Publications/Overview/Dragonflies/odonates_dragonflies.pdf" target="_blank">Dragonflies</a><br />(UPDATED file, 12 December 2005, with corrected photographs of scarlet marsh hawk (p.50) and coral tailed cloudwing (p.68))</li>
	<li class="gap-above-small">Part 3 - <a href="<?=RESOURCES_URL?>Other_Publications/Overview/Dragonflies/odonates_damselflies.pdf" target="_blank">Damselflies</a></li>
</ul>
