<h1>Report on University Science Education</h1>
<h2>&nbsp;</h2>
<h3>Foreword</h3>
<p>In recent years the Academy has felt increasingly concerned with the state of university education in science in the country. It has been widely realized that without a proper base in education it will not be possible to promote progress in science to attain the excellence that is a major concern of the Academy. Reflecting this concern, Council decided at its meeting on 30 July 1994 that an Academy Paper should be prepared, setting out Council's views on the problems of education in science in India as well as spelling out the action that can be taken by the Academy and various other agencies in the country. An Academy Panel was therefore constituted in July 1994, with Prof. N. Mukunda. FASc, as Chairman, to prepare a draft of the Academy paper on the subject. The Panel wrote to all Fellows seeking their views on the question, and many who were in Bengaluru joined the open meeting held by the Panel on 16 August 1994. The inputs from the Fellowship have been valuable to the Panel in drafting its report. I would like to take this opportunity to thank Professor Mukunda and his distinguished colleagues on the Panel for the extraordinary effort they have put into the preparation of a report that I am now happy to place before the Academy's Fellowship, the Government and the public for their consideration. Although numerous reports have been prepared on education in the country, and some by very distinguished academics, I hope it will be seen that the Academy has made a departure in several ways, in particular by setting out a course of action for itself.</p>
<p>I expect that this will be the first of a series of studies by the Academy on policy issues concerning science and technology in the country. By its very nature it is unlikely that a document of this type will have the unanimous approval of all Fellows of the Academy, but the procedure we have adopted ensures that the report now being released by the Council represents the views of the vast majority of the Fellowship. <strong>R. Narasimha President</strong>.</p>
<h3>UNIVERSITY EDUCATION IN SCIENCE</h3>
<h3>1. INTRODUCTION</h3>
<p>Following the expression of widespread concern on the state of university education in science in the country, the Council of the Indian Academy of Sciences decided that an Academy Paper should be prepared on the subject. Accordingly, the President appointed a Panel whose composition is shown in the Appendix. Its terms of reference were:</p>
<ol>
	<li>to assess the state of education in science in the country, particularly at the undergraduate level; and</li>
	<li>to propose such measures as may be considered appropriate to improve the quality of education in science through the combined efforts of universities, higher institutes of learning, government authorities, voluntary agencies and the Academy.</li>
</ol>
<p>This document is based on the report submitted by the Panel. In preparation for its work, a half-day symposium on "University Education in Science" was organized by the Panel on 16 August 1994 at the Indian Institute of Science, Bengaluru. In addition to all Fellows resident in Bengaluru, the faculty and students of the Indian Institute of Science, Raman Research Institute, Indian Institute of Astrophysics, and concerned faculty from Bengaluru University and selected colleges in Bengaluru were invited to the symposium. Four of the panel members presented, half-hour papers on the four major science streams - V. G. Bhide on physical sciences, A. Sitaram on mathematical sciences, M. K. Chandrashekaran on life sciences, and B. M. Deb on chemical sciences. There were also introductory remarks by the President, R. Narasimha, and brief invited observations by C. N. R. Rao and G. Padmanaban. Many Fellows present at the Symposium - including M.V.Bhatt, S. K. Brahmachari, R. Cowsik, V. K. Gaur, R. Narasimhan, J. Pasupathy, Phoolan Prasad, Raja Ramanna, P. N. Shankar, B. V. Sreekantan and N. Viswanadham - as well as Prof. S. Khatre of Bengaluru University, contributed to the discussions.</p>
<p>The Panel met on 16 and 17 September 1994 for detailed discussions, as well as on 27 September 1994 to finalize its report. The Secretary of the Academy in a circular letter to all Fellows informed them of the setting up of the Panel and invited them to convey their views to it. Close to fifty responses from Fellows were received, some containing suggestions relating to specific subjects. All of these, and the comments made during the symposium, have been taken into account in the preparation of this Paper.</p>
<p>The Paper is structured as follows: Section 2 recapitulates the dimensions of the problem of science education in the country, starting with a brief look at the school scene and then moving on to the undergraduate and postgraduate levels at colleges and universities. This Section also includes an account of frequently expressed perceptions of the current scene in university education in science. Section 3 reviews briefly some of the suggestions that have been made earlier by various concerned groups and agencies to tackle the problems set out in Section 2.</p>
<p>Section 4, in a sense the heart of this document, presents the views of the Academy on various aspects of the question of university education in science. Among the issues considered are the following: the role of Government agencies; the functioning of educational institutions; the contributions that national laboratories and R and D institutions can make to science education; patterns of curricula, flexible options for students, teacher training, needs of different groups of students; and urgently needed improvements in the teaching of particular subjects. The relationship between the social goal of equity and the academic one of recognising and supporting excellence has also been addressed, and ways have been suggested for a reorientation of the educational system by which these goals can be seen as complementing each other.</p>
<p>The recommendations are given in Section 5. They have been grouped separately into those that involve major agencies and wings of Government, and those where the Academy can take initiatives on its own. Section 6 gives a brief summary of the major recommendations, for quick and easy reference.</p>
