<h1>Report on University Science Education</h1>
<h2>&nbsp;</h2>
<h3>3. EARLIER SUGGESTIONS AND PROGRAMMES FOR COORDINATED ACTION</h3>
<p>In the face of the deteriorating situation described in the previous Section, there have been several carefully thought-out suggestions for positive action made by responsible and concerned academic groups in the country. Therefore, before going on to a discussion of what the Academy can do, both on its own and in concert with other bodies, it is useful to consider briefly some of these suggestions, at least in outline, if only to demonstrate that the desire to do something, and fairly specific proposals for action, have not been wanting.</p>
<h4>a) Planning Commission Initiative [4]</h4>
<p>A Working Group to suggest ways and means of improving university science education, especially at the undergraduate level, was set up by the Planning Commission in 1989. This Group prepared a detailed proposal, expressing the hope that the action suggested would be taken starting August 1990. Though this has not happened, the proposal itself is still worth scrutiny. This proposal, or possibly some suitable variant of it, would be a good starting point to reverse the many undesirable trends in the present situation.</p>
<p>The proposal involves working 'at three tiers, each aimed at a particular segment of the student population. They may be briefly described as follows:</p>
<p><strong>Tier I: </strong>This is aimed at the highly talented group of students, the number per year being estimated at about 700 (i.e., 0.5% of the total of about 1,50,000 students entering undergraduate science courses each year)*. The proposal is to introduce a very carefully planned five year Integrated M.Sc. programme in a few institutions (structured like the family of I.I.T.'s). They could be independent institutes, or alternatively the UGC could choose a few Centres in existing institutions, say 3 Centres to cater to Physics and Chemistry, 2 to cater to the Life Sciences, and 2 to the Mathematical Sciences. With seven such Centres, each could admit 100 students per year based on merit alone, through a common entrance test conducted nationwide. The courses in Year I would be common to * These and subsequent figures in this Section are estimates made be, the Planning Commission Working Group, and refer to 1989.</p>
<p>all streams, ensuring that the foundations of each major subject are properly covered. Years 2 and 3 would be like a B.Sc. (Honours) programme, involving one main subject leading up to the M.Sc., and two subsidiary subjects. At the end of Year 3, a successful student could either leave with a B.Sc. (Honours) degree, or proceed to M.Sc. Years 4 and 5 should bring the student to the threshold of research.</p>
<p>Every student should acquire basic levels of proficiency in mathematics, computers and electronics; and the entire programme should be challenging, and flexible enough to permit combinations of subjects like physics and biology, mathematics and biology etc. Students should be provided with reasonable scholarships to finance their education and major agencies such as DAE, ISRO and CSIR should be persuaded to assure career opportunities to the most successful students coming out of this course.</p>
<p><strong>Tier II: </strong>This is aimed at the next segment of the undergraduate science student group numbering about 24,000 per year (about 16% of the students entering each year). The purpose is to raise the general level of undergraduate science teaching at a large number of selected institutions spread all over the country. The UGC may select 20 colleges each year over a five year period - thus ultimately reaching a total of 100 colleges. Financial assistance should be provided to such colleges to formulate and introduce 3 year B.Sc. degree courses of high academic quality and content. Each college would admit 240 students per year, based on a locally conducted entrance test. Year I of the course would have a curriculum common to all students, while Years 2 and 3 would cover one main and two subsidiary subjects. By 'the time 100 colleges introduce such programmes, the annual admissions would reach 24,000.</p>
<p><strong>Tier III: </strong>Tiers I and II together would cater to almost 25,000 students, out of the total of 1,50,000 entering undergraduate science each year. The remaining 1,25,000 (constituting, 84% of the total) form such a large group that in order to improve matters for them it becomes essential to go beyond conventional systems and methods. Most of these students study in affiliated colleges many of which have indifferent faculty and inadequate infrastructure. To cope with the vast numbers involved, one has to employ new methods of communication and distance education such as video taping of lectures by outstanding teachers, preparing entire courses of lectures on tape, periodic teacher training programmes at nearby universities etc. The financial estimates made in 1999 by the Working Group for a full five year programme were as follows: Tier I - 25 crores, Tier 11 - 60 crores, Tier III - 30 crores.</p>
<h4>b) UGC Curriculum Development Centres Programme [6]</h4>
<p>The UGC set up these Centres in 1988 in various subjects, each Centre being located at a University Department. Their terms of reference included the assessment of the quality and content of existing curricula in various universities, and evolving new curricula at both undergraduate and post-graduate levels in each subject in order to promote excellence in teaching at these levels. As a result of the efforts of these Centres, detailed curricula have in fact been evolved for the B.Sc. (General) Course and for subject-specific B.Sc. and M.Sc. (say, in physics) courses. This careful work can provide the basis for updating and improvement by other bodies in coming years.</p>
<h4>c) Quality University Education for Scientific Talent - the QUEST Programme [7]</h4>
<p>This programme has been evolved by a group based at Panjab University, Chandigarh, and is similar in spirit to the Tier I Integrated M.Sc. programme described in subsection (a) above. The aim here is to train and produce highly competent scientists who are at the same time well rounded human beings. The courses during the first three years would be common to all students and would cover the basics of mathematics, physics, chemistry and life sciences. Also included would be computer programming and visualization, an introduction to earth sciences, and experimental courses which emphasize planning and designing of one's own experiments. After the common three year training, opportunities would be provided to branch out in different directions. At the end of the five year course, each student should be highly competent in a "principal" subject and quite well prepared in at least one other. By bringing home the unifying conceptual foundations of science, and also providing exposure to technology and problems of industry, each student should be able to act as a spokesman for science in society and have the self-confidence to attempt scientific solutions to practical real-life or field problems.</p>
<h4>d) The M.Sc. (Biotechnology) Programme of the Department of Biotechnology (DBT)</h4>
<p>The pioneering efforts of DBT in promoting post-graduate education and research have been fruitful in the life sciences area. Special M.Sc. courses in biotechnology in a selected group of institutions, with student scholarships provided by DBT and selection via a national level test, have, in addition to providing trained humanpower for the rapidly growing biotechnology industry, raised the general level of biology education in the country. A considerable amount of basic biochemistry and molecular biology is being imparted in these courses.</p>
<p>Efforts are also being made along similar lines by the Department of Electronics and the Defence Research &amp; Development Organization in other subjects.</p>
<h4>e) Efforts of the National Board of Higher Mathematics [8]</h4>
<p>The National Board of Higher Mathematics (NBHM), which is funded by the Department of Atomic Energy, has in the past taken many innovative steps to make it possible to spot, train and support talented students in mathematics. Apart from conducting the Indian National Mathematics Olympiad and training teams to participate in the International Mathematics Olympiad and running the 'Nurture Programme' for students who have qualified in the Indian National Olympiad and the Mathematics Training &amp; Talent Search Programme, the Board also offers scholarships for post-graduate students tenable at various institutions in the country.</p>
<h4>f) Initiatives of the Technology Information, Forecasting and Assessment Council</h4>
<p>As mentioned in Section 2, no reliable estimates of the requirements of trained scientific humanpower for various national tasks seem to be currently available. The Technology Information, Forecasting & Assessment Council (TIFAC), which functions within DST, has recently taken up the task of assessing these needs in some detail. Apart from the qualitative and quantitative aspects of science education, an effort is being made to ascertain the means to provide commensurate employment and career opportunities to specially trained science graduates.</p>
<p>TIFAC is working with agencies such as UGC, NCERT, the Department of Education, IIT'S, IIM's and AICTE in tackling these questions.</p>
<h4>g) INSA Reports on the National Status in the Sciences (1994)</h4>
<p>As part of its Diamond Jubilee activities, the Indian National Science Academy has recently commissioned special studies on the status of education in the various sciences, viz., physics, chemistry, etc. These will also be submitted as national status reports to such bodies as the International Unions of Pure &amp; Applied Physics and Pure &amp; Applied Chemistry. The document devoted to physics education [51, for instance, examines the situation at the +2, undergraduate, post-graduate and predoctoral stages, and makes several valuable suggestions for improvement in the quality of education offered; it also comments on the need for and growth in popular science exposition, links with industry, efforts by voluntary bodies etc.</p>
<p>Apart from the above, there have been State-level efforts at assessment and improvement of university education. As an example, we may mention the report of the Committee constituted by Mr. C. Subramaniam when he was the Governor of Maharashtra, to look at possible reforms in the universities in the State [9].</p>
<p>Before concluding this Section it must be acknowledged that the philosophical underpinnings of many of the ideas above, and those of the next Section, have been anticipated in two remarkable documents: (i) the Report of the University Education Commission, December 1948 - August 1949 [10], and (ii) the Report of the Education Commission, 1964-1966 [11], popularly known as the Radhakrishnan Commission and the Kothari Commission after their respective Chairmen. If (or perhaps, optimistically, we should say "when"!) some of the suggestions in the present document are implemented, it would be most instructive to examine these early and extremely thorough reports in detail, both for the broad philosophy of their approach to the role of education in our lives, and for specific details concerning implementation of their recommendations.</p>
