<h1>Report on University Science Education</h1>
<h2>&nbsp;</h2>
<h3>2. DIMENSIONS AND COMMON PERCEPTIONS OF THE PROBLEM</h3>
<p>Although the main focus of this document is university science education particularly at the undergraduate level, it is realized that undergraduate education is part of a continuum, starting with education at the school level and going on to research in science. It is therefore appropriate to remind ourselves, at least briefly, of some facts concerning school, undergraduate and post-graduate science education in India, before going on to reviewing suggestions already made by various individuals, institutions and agencies. The recommendations to be given later are to be viewed against this background.</p>
<p>In the following, representative figures of various kinds drawn from several sources will be presented. Although great accuracy cannot be claimed for these figures, they are sufficiently reliable for drawing the general conclusions set out in this Paper.</p>
<p>The number of school-going students, about 12 crores in 1985</p>
<ol>
	<li>has been continuously increasing at the rate of about 3% per year. However the number of well-equipped schools, in terms of laboratories, libraries and competent staff, is extremely small. Thus it has been estimated that no more than 60% of schools even have a blackboard, and less than 30% have any kind of library or laboratory facilities</li>
	<li>To cater to these basic needs, the amount of funding provided by the Government is estimated at about 15% of the total annual school educational budget of Rs.2500 crores</li>
	<li>This works out to Rs.375 crores, i.e. approximately Rs. 30 per student per year! The remaining budget allocation is used up for salaries and maintenance of establishments. As a result, the vast majority of schools are ill-equipped to impart a reasonable science education; yet the few that do so manage to maintain a high level of enthusiasm both among teachers and students.<br />
	Less than one percent of the students who complete the 10+2 school years go on to science education at college level. While the total number of students in all three years of undergraduate science courses has risen from about 1,28,000 in 1950 to 7,25,000 in the late eighties</li>
	<li> the percentage of the total student population choosing science after school has dropped over the same period from 32% to about 19% today. Undergraduate education is primarily imparted in a * Numbers in brackets indicate references or notes listed at the end of the document large number of affiliated colleges (about 6000 at present)</li>
	<li>but generally not in university departments. The vast majority of the affiliated colleges are ill-equipped.</li>
</ol>
<p>We may also keep in mind that, of the total university output of undergraduates each year, approximately one-third are in the sciences. One can also ask: how many really gifted and potentially creative science students are produced each year in the whole country, who go on to do research and work for a Ph.D. in Indian institutions? A reasonable estimate, based on the collective experience of many academics in their own institutions is that this number is not much more than 150-200. (As an illustrative example, the total number of Ph.D.'s awarded by the Indian Statistical Institute in the sixteen-year period 1979-1994 is about 120.) Typically, the same candidates get selected for admission in all the major institutions in the country for research. Thus the number of students who are suitable and who also opt for research is appallingly small.</p>
<p>Against this background, we review briefly the commonly held and expressed perceptions among the members of the academic community involved in higher education and research about the present state of science education in Indian colleges and universities. There are of course fortunate exceptions, but the general view is that standards in all respects have declined rapidly and alarmingly, and unless something is done soon to remedy the situation the country is definitely heading for disaster. This is more or less uniformly the opinion expressed in the letters written by Fellows to the Panel. One quite pessimistic view is that it may already be too late to prevent disaster. On specific aspects of the whole situation, we may summarise frequently articulated views as follows.</p>
<p>a) There has been an alarming drop in the quality of students who opt for higher studies in the sciences after school level. The best products from schools choose to go for courses in engineering, medicine and commerce, the next most talented group opt for administrative services, bank careers and the like those that pursue science at the undergraduate level are then largely drawn from the residue.</p>
<p>b) As against this, there has been no careful assessment of the country's needs for talented scientists in different spheres. The needs are obvious in sectors such as defence, space, atomic energy, health, agriculture and related fields, apart from the universities. The absence of quantitative estimates of the number of persons needed in the years to come may have contributed to the present problems. Well planned efforts to attract, train and retain appropriate numbers of scientists, to pursue a professional career in science in this country, are essential to prevent a crisis in the near future.</p>
<p>c) In contrast to the situation a few, decades ago, students, parents and indeed society as a whole do not presently view a career in science as rewarding or challenging, or even as offering a satisfying professional life. Career opportunities in science are perceived as limited, and as being not at all comparable materially with other professions. Intimately related to these negative impressions is the fact that faculty positions in colleges and universities appear lacking in prestige and respect, and in any case what young people see all too clearly is rampant inbreeding in most educational institutions.</p>
<p>d) The National Science Talent Search awards scheme instituted in 1964 was definitely a very worthwhile attempt to attract the best and most highly motivated students to devote themselves to careers in science. However even here the necessary follow-up steps to retain and provide for such students have been missing. In 1977 this scheme was enlarged to the National Talent Search award scheme, to include areas other than science. By around the mid- to late eighties only about 10% of the total number of awardees were opting for science at the undergraduate level; and the number going on to the post graduate level was even less [4].</p>
<p>e) It is commonly felt that the maximum damage to our students occurs after they come out of the school system and enter the undergraduate level (occasionally even at the +2 level). It is at this stage that all curiosity, self-confidence, enthusiasm and eagerness to learn are killed. Added to this are poor methods of evaluation and debilitating memory-based examining systems. The products of Indian undergraduate programmes are definitely poorer than their counterparts in developed countries, indeed much more so than at the 10+2 level. The burden of undoing and repairing the damage suffered at the college level has then to be borne by education at the post-graduate and research levels.</p>
<p>f) The options available to undergraduate students entering our institutions today are limited and inflexible. The division into engineering and medical streams at the +2 level itself contributes to the problem. Practically nowhere can an undegraduate student hope to pursue emerging combinations like biology and mathematics or biology and physics. One still has to choose from old-fashioned combinations like Physics. Chemistry and Mathematics or Chemistry, Biology and Zoology. In this respect the situation has worsened even in the Indian Institutes of Technology, which were initially quite flexible and open in course and subject combinations available to students. The option of students moving from the engineering stream to science is also rarely exercised. With this absurd and self-created inflexibility, a Ramanujan would never make it today.</p>
<p>g) In most universities and affiliated colleges one finds low educational standards and a poor academic environment. Colleges are generally under-equipped, overcrowded and poorly staffed. Not being directly involved in the framing of syllabi or in the evaluation process, it is perhaps not surprising that most teachers become demotivated and are seen to be uninspiring. Questions from students are often discouraged, and experiments and demonstrations are few. Due to lack of experimental facilities, science is taught unimaginatively, and learnt by rote. Generally routine and unexciting topics are taught, basic concepts are poorly covered, and at the higher levels teaching remains divorced from research. Quality and excellence in teaching go unrecognized and unrewarded; the few good teachers there are work under trying conditions. All this has a snow-balling effect - the generally low standards of the output at the undergraduate level get reflected among the entrants to post-graduate education and research.</p>
<p>h) Too many universities and institutions have been established over the years without giving adequate thought to the availability of teachers of acceptable quality. Without any attempts to correct the ills of existing institutions, all too often new ones are created only to face the same problems later.</p>
<p>i) It is widely felt that one cause for the sorry state of affairs outlined above is the government's policy of the past half century of establishing chains of specialised research institutions and national laboratories outside the university system, without proper and healthy linkages to the latter. This policy, especially the disproportionate funding of these institutions, has deprived universities of both talent and material support. Even worse, the access of young motivated students to leaders in various fields of science - natural in a university setting in developed countries and so essential to creative work at a young age - has become virtually impossible. Thus the soil where scientists of the future should grow has been deprived of some of its most important nutrients.</p>
<p>j) There has been hardly any initiative or involvement by private nongovernmental sources of support towards higher levels of education and research. Endowed chairs, industry-supported specialised laboratories and the like are conspicuous by their absence. This is particularly unfortunate since private enterprises depend on products of the educational system for their own needs.</p>
<p>k) As a result of national-level discussions and suggestions for mechanisms to encourage and support scientific research, many schemes have been established by Government agencies, and these have in fact done quite well. Examples are the Science and Engineering Research Council within the Department of Science and Technology, the COSIST programme of the University Grants Commission (UGC) and the (now-abandoned) University Leadership Programme. However, in the educational sphere, though on several occasions studies and recommendations have been made to improve the situation, there has been no sustained follow-up action. Even the series of teacher-training schools held successfully in the 60's and 70's, with support from the U.S. National Science Foundation, were discontinued due to lack of support from the Government. As a result, the enthusiasm for excellence in education has been lost.</p>
<ol>
	<li>With increasing political interference in higher education, the pursuit of excellence has disappeared and given place, among other things, to commercialisation of education. The twin aims of social equity and academic excellence are being seen as opposed to each other. There is no intellectual debate on these overlapping problems, and it is being left to the judiciary and the political leadership to determine the directions open to society.</li>
</ol>
<p>From this sampling of frequently heard opinions it is clear that the problems of university science education, seen in totality, are manifold, and that there has been room for continued criticism and complaint. Under these circumstances the Academy considers that there is a need to find ways in which it can help identify and reach out to the gifted, save as many of them as possible for the pursuit of science, and make them feel that it is still worthwhile and deeply rewarding to fashion careers in science.</p>
