<h1>Report on University Science Education</h1>
<h2>&nbsp;</h2>
<h3>5. RECOMMENDATIONS</h3>
<p>The recommendations are presented here in two groups: first those that involve national bodies, agencies, the educational system, research laboratories and industry; second, those that depend mainly on initiatives to be taken by the Academy. Some overlap with the views presented in Section 4 is retained to make the recommendations self-contained.</p>
<h4>A. General Recommendations</h4>
<p><strong>Functioning of Colleges and Universities, and role of national laboratories</strong></p>
<p>The absolute minimum that students and society should demand from universities and colleges is that they run as announced in schedules, hold classes and examinations on time, and declare results on time. This can only be achieved by sustained pressure from students and the public, and removal of political influence on university functioning. Maintaining strict schedules will facilitate comprehensive and thorough coverage of material.</p>
<p>An important aspect is continuous teacher training and upgradation of knowledge through summer and refresher courses. Here the experience of the chain of Academic Staff Colleges has not been good. Attendance at these courses is used largely as a prerequisite for promotion, and only 15% to 20% of those who attend have serious interest in the subject. The selection of the participants is also generally not in the hands of the course organisers. Therefore, attendance at refresher courses and training programmes for teachers must be separated from promotions, and the organisers must be allowed to select participants as -well as examine them at the end of each course.</p>
<p>Some of the proposals described in Section 3 involve creation of new institutions or centres. The Council strongly feels that these should be within the overall university system, but should be administratively independent and autonomous [12].</p>
<p>In particular, we urge the adoption of a three-stream approach to undergraduate education in science, in the spirit of the framework proposed by the Working Group of the Planning Commission, as described earlier in Sections 3 (a) and 4. In the first two streams, leading to an improved B.Sc. degree and the B.Sc. (Hons) and integrated M.Sc. degree programmes, the involvement of at least a few university departments in undergraduate teaching, in addition to their regular postgraduate teaching and research work, is essential, and such universities should offer all four of the basic subjects of Physics, Chemistry, Mathematics and Biology at similar levels. The course options for students in the third or Applied Science stream need to be drastically redesigned, so that apart from a foundation in basic science a wide variety of options of a more vocational or practical nature are available; we are convinced that the traditional undergraduate course does not really address the needs of this group. Redesigning the undergraduate course on such lines will be a complex task, which could be the subject of future detailed discussions.</p>
<p>Along with the recommendation for the introduction of strong Integrated M.Sc. programmes in selected institutions, the Academy also urges the introduction of Integrated Ph.D. programmes in the four main science subjects. Such a scheme presently exists in Chemical Sciences, Physical Sciences and Biological Sciences at the Indian Institute of Science, Bengaluru. Such programmes, the input to which would be gifted and motivated B.Sc. graduates, need to be very carefully structured and offered at a small number of select institutions capable of sustaining them.</p>
<p>In the Max Planck Institutes of Germany and CNRS in France, there is a tradition of scientists in national laboratories being given the opportunity to teach and interact with students at adjoining universities. In the process, such scientists are offered the academic title of Professor at the university. Such a relationship between universities and national laboratories makes eminent sense in our country today; already, as an example, one may mention courses taught jointly by scientists of the National Chemical Laboratory, Pune, and faculty of Poona University. At a more individual level, one should encourage the notion of adjunct faculty, which would enable outstanding scientists outside the university system to participate in teaching in universities. One step in this direction might be to create a fund to support teaching and research ventures undertaken jointly by faculty in universities and scientists in national laboratories.</p>
<p><strong>Role of Government Agencies and Industry</strong></p>
<p>Looking at the present state of functioning of most of our universities, it is necessary for the UGC and Parliament to step in and make them more than mere examining bodies; instead they must be enabled to become centres of learning and excellence. To achieve this objective, funding provided to colleges and universities must improve, and at least at a few places quality science education centres must be started. One way to do so would be to implement the recommendations made by the Planning Commission Working Group, sketched in Section 3 (a). In addition, a system of accreditation of university science departments should be introduced; this should be carried out by a central and autonomous body not susceptible to local political pressures.</p>
<p>The efforts of DBT in the life sciences and NBHM in mathematics have been mentioned earlier. Other major agencies such as DAE, DOE, ISRO and DST must be persuaded to support selected, good M.Sc. programmes in physics, chemistry, biology and mathematics. The intention must be to support education in the basic sciences, not immediately linked to the needs of these agencies - such seemingly altruistic support will surely help them in the long run. The institutions to be chosen for such agency support could be picked, on the basis of faculty and syllabi, by the Academy or any other body of standing. The agencies should provide scholarships, support setting up of laboratories, donate equipment, and do all this without insisting on too early specialisation.</p>
<p>Industry too - the Confederation of Indian Industries (CII), the Federation of, Indian Chambers of Commerce and Industry (FICCI) and the Associated Chambers of Commerce (ASSOCHAM) for example - should come forward with scholarships for P.G. students and support to laboratories. As is the practice in Germany, for instance, the chemical and pharmaceutical industries should be persuaded to give essential solvents and basic chemicals to U.G. and P.G. institutions for their chemistry programmes. In the same spirit, the Indian Chemical Manufacturers Association (ICMA) could be induced to provide help in improving education in chemical sciences. Groups of companies with common interests could also be targetted. Other sources, for example international bodies like UNESCO, could also be asked for similar support in all areas of science.</p>
<p>Wide publicity should be given to educational opportunities in the sciences, as well as to career opportunities in industry and elsewhere for science graduates. This could be done through the proposed new science magazine recommended below (in B (vi)).</p>
<h4>B. Academy Initiatives</h4>
<p><strong>Efforts by the Academy through the Fellowship</strong></p>
<ol>
	<li>Council proposes to commission a group of Fellows to prepare two volumes on what students should know in each area of science respectively at the B.Sc. and M.Sc. levels, and as preparation for embarking on a Ph.D. programme. Such preparation should be comparable to the level of attainment seen at the Ph.D. qualifying examinations of good U.S. universities. The volumes may be brought out through private publishers under Academy auspices, and will reflect the suggestion made in Section 4 that for the first two years of B.Sc. all science students should have a largely common curriculum. Some description of course combination options and careers should be included.</li>
	<li>Council proposes to commission and support the writing of brief expository monographs ("appreciation courses") on scientific topics, in the style of the MIR publications of the former U.S.S.R. Some could be written by Fellows, some by others by invitation.<br />
	Council also proposes to commission preparation of modem science texts at U.G. and P.G. levels as well as more informal Lecture Notes where necessary. In cases where classic texts are available in inexpensive editions (many mathematics texts, the Feynman Physics lectures, etc.), the writing of supplementary texts leading up to the classics need to be supported. Reprinting of other classics with permission, sometimes accompanied by commentaries, will also be encouraged.<br />
	Other types of monographs whose writing would be similarly encouraged are "bridge courses", which would help non-experts get an overview of a scientific topic, and also advanced books on specific topics.
	</li>
	<li>Council plans to commission teams of Fellows to devise sets of experiments (say about a hundred) in each of the basic sciences, which bring out fundamental principles in an appealing way, wherever possible using inexpensive and commonly available materials.</li>
	<li>In cooperation with experienced teachers and expositors, and working with existing centres such as the EMRCs at Pune and Hyderabad, the Academy will offer assistance in production of radio and TV programmes on science, and video tapes to supplement class room instruction at school and college levels. These could also be in regional languages, and explore "alternative" methods of teaching. A library of 40-50 taped lectures, covering substantial parts of the undergraduate curriculum, could also be created.</li>
	<li>The Academy will attempt to periodically assess the, state of affairs in education in each major scientific field and publish its findings, giving current trends, pointing out lacunae, highlighting possible opportunities, and offering suggestions about areas needing special effort.</li>
	<li>Council proposes to launch a journal of science specially intended for science students and educated lay persons interested in science. The editorial, intellectual and financial backing of the Academy will be available to sustain such an effort. The journal will contain expository articles, descriptions of new teaching methods and innovative experiments, science news, historical notes etc. Information on course openings and facilities in various institutions might be included in such a journal, as well as advertisements from prospective employers of science graduates.</li>
</ol>
<p><strong>Interaction with student and teacher communities</strong></p>
<ol>
	<li>Subject to the availability of resources, Council will establish a programme wherein Fellows would be invited to identify one or two college students each year (within some overall limit) for placement in a (summer) programme organized or assisted by the Academy. Such students would be supported to spend some time - say two months or so - working and studying under a Fellow's guidance. Such short term research experience will help the student to use his or her spare time productively, and it is hoped that many bright youngsters may thereby be motivated into pursuing careers in scientific research.</li>
	<li>A similar programme at the college and school teacher levels is also being considered, with Academy support for summer training programmes for them. This will not be on the rigid lines of similar current programmes. The participants would be selected by the Academy on the strength of their motivation, rather than on seniority or as an aid to their promotion.</li>
	<li>Similar to the series of Discussion Meetings supported by the Academy, Council proposes a series of Academy seminars for chosen college teachers and promising students, which may be organized by groups of Fellows in each subject area. Students could speak to audiences of other students, teachers and Fellows on topics chosen with guidance. This would promote popularisation of science as well as contacts between Fellows, students and teachers. (iii) An Extension Lecture Programme, similar to the UGC supported programme at IISC for example, will be set up under Academy auspices. Fellows in each region would give lectures on a list of topics made available to nearby schools and colleges.</li>
	<li>Council proposes to invite a few college and university teachers to its annual and mid-year meetings as guest participants. This will increase personal contacts between Fellows and good teachers, and be a form of recognition for the latter.</li>
</ol>
<p>The above initiatives demand linkages with reputed publishers and additional financial resources, which will be sought by the Academy from Government and private sources.</p>
<p><strong>Link with teaching departments and institutions</strong></p>
<p>Council recommends to University science departments and national laboratories that they produce brochures containing helpful information about their activities for the guidance of students. This is common practice in developed countries, but in contrast such information is rather difficult to obtain for a student interested in working in Indian institutions. The Academy could evolve a suitable format for such brochures, and assist when necessary in disseminating the information available in them.</p>
<p><strong>Contacts with national bodies, agencies, etc.</strong></p>
<ol>
	<li>Council proposes to set up a Committee to carefully examine the goals of equity and excellence from new perspectives, and to arrive at ways of restructuring the overall educational system so that these goals are no longer seen as mutually exclusive. The views of the Academy will be widely publicised, in the expectation that this debate takes a new and fruitful turn, showing us a way out of the corner into which the country has pushed itself by so far relying solely on political and judicial approaches</li>
	<li>The Academy expresses strong support for the Integrated M.Sc. programmes along the lines described in Section 4. The Academy is willing to offer its assistance in the selection of institutions to establish such programmes and in the preparation of appropriate syllabi, including experiments.<br />
	The Academy also recommends the setting up of Integrated Ph.D. programmes at a few select institutions, which would take students with a good undergraduate degree and give them the necessary training (including course work) to bring them to the threshold of research. Suitable guidance could then be offered to enable them to work towards a Ph.D. A Master's degree could also be awarded at a suitable intermediate stage.<br />
	It is also recommended that the usual Ph.D. programmes, which take students after a Master's degree, should include some pre-Ph.D. courses to bring students up to the same level as in the Integrated Ph.D programme. In some of the advanced courses offered in the integrated programmes or as part of the requirements for the Ph'D. programmes, students from different institutions may be pooled together, especially when the numbers involved at each institution are small. While the above recommendations relate to research level training in science, the Academy strongly endorses the pattern of U.G. science education as outlined in Section 4a.
	</li>
	<li>The Academy also endorses the need to introduce special M.Sc. courses in different branches of - science, in the spirit of the, DBT programme. It is recommended that the science departments and agencies of, the Central Government, provide, scholarships to such students and support the setting up of laboratories and other facilities for such courses.</li>
	<li>The views of the Academy on the structure and content of science education at the U. G. and P. G. levels, as suggested in Section 4, and on the support needed by universities and colleges as well as on the way they should function, will be made widely known to the general public, the student and teacher communities, other academic societies, and Government bodies such as the Planning Commission, the Department of Education, and the UGC.</li>
</ol>
