<h1>Information for Authors</h1>
<h2>Journal of Genetics</h2>
<h3>GENERAL</h3>
<p><em>Journal of Genetics</em> covers all areas of genetics and evolution, but a contribution must have one of these subjects as its focus and be of interest to geneticists for acceptability. Papers not explicitly genetical, but addressing evolutionary issues of interest to geneticists can also be considered for publication. All contributions undergo editorial and peer review. Colour illustrations are printed free of charge. PDF files of all published articles are downloadable free of charge from the open access journal website (http://www.ias.ac.in/jgenet) for academic purposes.</p>
<h3>CATEGORIES OF MANUSCRIPT</h3>
<p><em>Journal of Genetics</em>Journal of Genetics will consider full-length research articles, short research notes, research commentaries and hypothesis pieces. Review articles, book or software reviews, obituaries and essays of a more general nature on ideas and trends in genetics and evolution (perspective or viewpoint pieces) will typically be solicited; prospective authors of such contributions are encouraged to contact the editors with a brief proposal prior to submission.</p>
<p><strong>Research article: </strong>The regular full-length article, reporting results of original research; no word / reference / display item limit; should include an abstract of about 250 words.</p>
<p><strong>Research note: </strong>A brief report (less than 2000 words text; up to two figures or tables; up to 20 references) on an interesting, somewhat preliminary result; no abstract; the first paragraph should be a summary of note in about 100–150 words.</p>
<p><strong>Research commentary: </strong>A brief summary (less than 3000 words text; up to two figures or tables; up to 20 references) of recently published paper(s) on a common theme of some general interest, placing the work discussed in a broader context; no abstract.</p>
<p><strong>Hypothesis: </strong>A brief description (less than 2500 words text; up to two figures or tables; up to 20 references) of a new hypothesis, or speculative idea; no abstract.</p>
<p><strong>Viewpoint: </strong>A brief comment ; (less than 2500 words text; up to two figures or tables; up to 20 references) on issues in genetics research or education, technological applications of genetics, or the history of genetics and its impact on society; no abstract.</p>
<p><strong>Correspondence: </strong>A brief comment/critique on a paper recently published in Journal of Genetics (less than 2500 words text; up to two figures or tables; up to 20 references); no abstract. Authors of the original paper will be invited to submit a response.</p>
<p><strong>Review article: </strong> No word / reference / display item limit; should include an abstract of less than 300 words.</p>
<p><strong>Perspectives: </strong>A general article looking at some major issue in genetics research or education, technological applications of genetics, or the history of genetics and its impact on society; no word / reference / display item limit; should include abstract of less than 300 words.</p>
<p><strong>Obituary: </strong>No word limit.</p>
<p><strong>Book/software/website review: </strong>No word limit.</p>
<p><strong>Online resources: </strong>Brief reports of the development and/or routine use of molecular markers for assessing genetic variability within and among species, as well as reports outlining useful pedagogical approaches/methods in genetics teaching, or development/modification of software that could be useful in genetics research or teaching (less than 2500 words text; less than 25 references; no abstract; no upper limit on the number of display items). Papers accepted under this category will only appear online, with a listing of titles of papers appearing online during the preceding four months in each print issue.</p>
<h3>SUBMISSION</h3>
<p>Submitted manuscripts must not have been published previously nor be under consideration for publication elsewhere. Moreover, submission to <em>Journal of Genetics</em> will be deemed to imply that the manuscript will not be submitted elsewhere if accepted. The decision of the editors is final in the matter of acceptability for publication.</p>
<p><strong>Electronic via the Web only: The journal only accepts submissions via Editorial Manager on the Web at <a href="http://www.editorialmanager.com/jgen/" target="_blank">http://www.editorialmanager.com/jgen/</a>. Authors are urged to use this facility.</strong> The website has online help, and general information on acceptable file formats (in the section ‘Editorial Manager system requirements’). Authors whose submissions do not conform to the guidelines given in this section for file formats and in the sections below will experience delays in processing. For text, TXT, LaTeX and Microsoft Word files are acceptable. For illustrations, the preferred file formats are:</p>
<ol>
	<li class="gap-above-small">Colour and greyscale illustrations: TIFF files 300 dpi print resolution (at final print size) (in CMYK colour mode for colour illustrations), or PostScript files (with a TIFF preview).</li>
	<li class="gap-above-small">Monochrome line drawings: PostScript files (with a TIFF preview), or TIFF files 1200 dpi print resolution (at final print size).</li>
</ol>
<p>Note that Microsoft Word and Microsoft PowerPoint files, which are frequently submitted for illustrations, are not acceptable. All lettering in illustrations should be in sans-serif type, preferably Helvetica, and as close to 8 point size as possible at final print size; hairlines should not be used, minimum line thickness should be 0.2 mm or 0.5 point. For accepted submissions, the publishing office may require good prints of illustrations for typesetter’s and printer’s use. Authors who have insurmountable difficulties that preclude Web submission should contact the editorial office by email at jgenet@ias.ernet.in.</p>
<h3>PERMISSIONS</h3>
<p>Authors should submit written permission from appropriate sources for material to be included that has been published elsewhere.</p>
<h3>FORMAT</h3>
<p>The current format of the journal is: trim size 210 mm width x 280 mm height, page print area 175 mm x 250 mm (including header and footer), pages in two equal columns of 85 mm.</p>
<h3>TITLE, AUTHOR DETAIL, KEYWORDS</h3>
<p>The title should be brief, interesting and comprehensible to a nonspecialist reader, and contain words useful for indexing. Serial titles should be avoided. A short running title (of not more than 55 characters including spaces) suitable for page headers, and up to six keywords useful for inclusion in the annual subject index should be provided. Full names and affiliations of all authors, and complete postal and email addresses are required.</p>
<h3>ABSTRACT</h3>
<p>An abstract is required only for some categories of manuscript. The abstract should convey the essence of the contribution even to a nonspecialist reader. For a research article, the abstract should include a few sentences of background to the work, the rationale, and the main results and conclusions. First person (singular, if one author) and active voice are preferred. Abbreviations are discouraged. Abstracts should not include citations to references.</p>
<h3>MAIN TEXT</h3>
<p>This should be divided into sections with first-level headings (centred and in boldface) such as Introduction, Materials and methods, Results and Discussion. These may also be descriptive headings, such as may be appropriate, for example, for review articles, or theoretical papers. There may be subsections with short, descriptive headings. Major subsections within sections may be placed under second-level headings (flush left, in italics and boldface, free-standing); these may contain further subsections under third-level headings (flush left, in italics and boldface, and text runs on after a colon). Sections and subsections are not numbered. Footnotes are not allowed. Where appropriate, first person and active voice are preferred. Spelling should conform to the preferred spelling of the latest edition of the Concise Oxford Dictionary.</p>
<h3>CONVENTIONS</h3>
<p>Authors should follow internationally accepted conventions with regard to units, symbols and abbreviations. Only SI units of measurement and standard abbreviations should be used. Binomial names of organisms are italicized. Special care must be taken with regard to biochemical and genetic nomenclature. Genotype names and symbols are always italicized, but phenotype, including name or symbol of the protein product of a gene, where this is well characterized, is roman. Authors are urged to take great care in distinguishing between genotype and phenotype clearly in all sections of the manuscript, including tables and illustrations.</p>
<h3>STATISTICS</h3>
<p>Guidelines on use and presentation of statistics have been published by <em>Proceedings of the Royal Society of London, Series B: Biological Sciences,</em> and are usually printed in the last issue of every volume of that journal. <em>Journal of Genetics</em> encourages authors to consult those guidelines.</p>
<h3>TABLES</h3>
<p>All tables should be numbered serially, in arabic numerals, in order of appearance. Tables should be as self-contained as possible, with a descriptive but brief title. Details not mentioned in text and explanations may be given below the table as footnotes. Row and column headings should be in lower case, except for the first letter of heading word or phrase, first letter of proper names, or where capitals are essential. Tables should be arranged as far as possible to conform to printed column or page size. Tables should not be prepared with the ‘Insert Table’ or similar option of word processing or other software, but should be typed as text, with tabs for delineating columns.</p>
<h3>ILLUSTRATIONS</h3>
<p>All figures should be numbered, serially in arabic numerals in order of appearance. Parts of multipart figures, where these are absolutely necessary, should be labelled (a), (b), (c), etc. (lower case). Authors should take responsibility for neat and correct arrangement of multipart figures. Figure legends should not be included in figure files but should be included in the file of the text. Line drawings should be sharp, and include all lettering that is necessary. Lettering should be in lower case, except for the first letter of label word or phrase, first letter of a proper name, or where capitals are essential. The font should preferably be a sans-serif type, and letters at final print size should be as close to 8 or 9 point type as possible. All symbol, nomenclature, genotype/phenotype and other conventions apply to figure lettering. Submitted drawings will ideally be about 50 to 100% larger than the expected final print size. Authors should try as far as possible to compose figures to fit one-column or two-column width in print. Individual parts in multipart groupings should be as close to each other as possible, with the parts labelled. Photographs should be sharp and high-contrast, and any labelling (such as arrows or letter symbols) should be clear. Photomicrographs must have a scale bar applied directly on the illustration, and the exact length indicated above the bar or stated in the legend. Colour should be used only where it is essential. DNA, RNA and protein sequences will be treated as figures, and the instructions for line drawings above apply.</p>
<h3>REFERENCES</h3>
<p>Citations in the text should be by name and year, not number, in chronological order and then alphabetically for the same year, and enclosed in parentheses. When there are two authors, the citation should include both names (e.g. Guo and Thompson 1992). When there are three or more authors, the citation should have only the first author and ‘<em>et al</em>.’ (e.g. Calafell <em>et al</em>. 1996). Two or more citations are separated by a semicolon. References should be listed at the end in alphabetical order of author. When several references have the same author or first author, single-author works are listed first chronologically, then two-author works in alphabetical order of second author and then chronologically, and multiauthor works third but chronologically. Letter labels should be used (e.g. 1997a, 1997b) in case of works with the same author/authors and of the same year. When there are many more than six authors, it is preferable to name only the first six and use ‘<em>et al</em>.’. Unpublished observations and personal communications should not be included in the list of references, but should be cited within parentheses in the appropriate place in the text with the full names of the sources. The list of references may include papers accepted but not yet published; such references should include the journal name and ‘in press’ in parentheses at the end. Information from material submitted for publication but not yet accepted should be cited only in the text as ‘unpublished observations’ with full names; these should not be included in the list of references. Abstracts should not be used as references. Authors should consult the current or a recent issue of the journal for style, but a few examples are given below. Journal name abbreviations and book titles are in italic, volume number is in bold. There should be a space between initials in author names.</p>
<p><strong>Examples:</strong></p>
<p>Gibert P., Moreteau B., Moreteau J.-C., Parkash R. and David J. R. 1998 Light body pigmentation in Indian <em>Drosophila melanogaster:</em> a likely adaptation to a hot and arid climate. <em>J. Genet.</em> <strong>77</strong>, 13&ndash;20.</p>
<p>Sambrook J., Fritsch E. F. and Maniatis T. 1989 <em>Molecular cloning: a laboratory manual</em>, 2nd edition. Cold Spring Harbor Laboratory Press, Cold Spring Harbor.</p>
<p>Via S. 1994 The evolution of phenotypic plasticity: what do we really know? In <em>Ecological genetics</em> (ed. L. A. Real), pp. 35–57. Princeton University Press, Princeton.</p>
<h3>ACKNOWLEDGEMENTS</h3>
<p>These should follow immediately after the end of the main text. In references to granting agencies, the names should be written out fully.</p>
<h3>PROOFS</h3>
<p>Authors are requested to prepare their manuscript carefully and in accordance with these instructions to avoid delays and to minimize corrections and alterations in copyediting. The corresponding author will receive page proofs, typically as a PDF file, and a reprint order form, by email. Corrections should be emailed within two or three days to the editorial office. Alterations of more than a minor nature cannot be accepted at this stage. No further proofs will be sent.</p>
<h3>REPRINTS</h3>
<p>Fifty reprints will be supplied to the corresponding author free of charge. Extra reprints may be ordered on the reprint order form sent with proofs. PDF files of published articles are available on the open access journal website at http://www.ias.ac.in/jgenet.</p>
<h3>COPYRIGHT</h3>
<p>Indian Academy of Sciences, publisher of the journal, will acquire copyright over all published material. Authors may reproduce their published material elsewhere subsequently with the usual acknowledgement to ‘<em>Journal of Genetics</em>, published by Indian Academy of Sciences, Bengaluru’ and the volume and page details, but a request to do so will be appreciated and also serve to keep the editorial office informed. Third parties who wish to reproduce published material should write to the editorial office for permission.</p>
<h3>Excerpts from the Publication Authorization and Copyright Transfer Form (PACT):</h3>
<p>vi) Copyright to the author’s work, including title, abstract, complete text, tables, graphs, figures and any later errata, is hereby transferred to the Indian Academy of Sciences, in case it is accepted for publication, for both online and print versions.</p>
<p>It is further noted that, consistent with the copyright transfer, item (vi) above, the authors may use this work after publication by the Indian Academy of Sciences, in whole or in part, in any or all of the following ways without seeking permission from the Academy provided that reference to the original publication in the concerned Academy journal is always made:</p>
<ol type="a">
	<li>Reprinting in a book or reprint collection of the author for noncommercial purposes.</li>
	<li>Inclusion in a thesis or dissertation for a research degree of any institution.</li>
	<li>Presentations in Conferences, Colloquia, Seminars.</li>
	<li>Classroom use as part of course material, including distribution of photocopies.</li>
	<li>Inclusion of the published work with no changes on the author’s personal website or institutional archives/repositories.</li>
	<li>Distribution of photocopies/PDF files online to colleagues for academic purposes.</li>
</ol>
<p>The jurisdiction for all disputes concerning submitted articles, published material, subscription and sale will be at courts/tribunals situated in Bengaluru city only.</p>
<h4><a href="<?=BASE_URL?>Journals/Overview/Academy_Policy_on_Plagiarism">Academy Policy on Plagiarism</a></h4>

